name: harmony_sdk
version: 0.0.8
homepage: https://github.com/harmony-development/harmony-dart-sdk
environment:
  sdk: ">=2.12.0 <3.0.0"
description: >-
  An idiomatic dart SDK for the Harmony chat protocol, allowing one to
  write clients, bots, and other things speaking it.
dependencies:
  protobuf: ^2.0.0
  fixnum: ^1.0.0
  async: ^2.8.2
  tuple: ^2.0.0
  http: ^0.13.4
  web_socket_channel: ^2.1.0
