///
//  Generated code. Do not modify.
//  source: chat/v1/chat.proto
//
// @dart = 2.12
// ignore_for_file: annotate_overrides,camel_case_types,unnecessary_const,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type,unnecessary_this,prefer_final_fields,deprecated_member_use_from_same_package

import 'dart:core' as $core;
import 'dart:convert' as $convert;
import 'dart:typed_data' as $typed_data;
import 'guilds.pbjson.dart' as $7;
import '../../harmonytypes/v1/types.pbjson.dart' as $0;
import 'channels.pbjson.dart' as $6;
import 'messages.pbjson.dart' as $4;
import '../../emote/v1/types.pbjson.dart' as $1;
import 'permissions.pbjson.dart' as $5;
import 'stream.pbjson.dart' as $8;
import '../../emote/v1/stream.pbjson.dart' as $2;
import '../../profile/v1/stream.pbjson.dart' as $3;

const $core.Map<$core.String, $core.dynamic> ChatServiceBase$json = const {
  '1': 'ChatService',
  '2': const [
    const {'1': 'CreateGuild', '2': '.protocol.chat.v1.CreateGuildRequest', '3': '.protocol.chat.v1.CreateGuildResponse', '4': const {}},
    const {'1': 'CreateInvite', '2': '.protocol.chat.v1.CreateInviteRequest', '3': '.protocol.chat.v1.CreateInviteResponse', '4': const {}},
    const {'1': 'CreateChannel', '2': '.protocol.chat.v1.CreateChannelRequest', '3': '.protocol.chat.v1.CreateChannelResponse', '4': const {}},
    const {'1': 'GetGuildList', '2': '.protocol.chat.v1.GetGuildListRequest', '3': '.protocol.chat.v1.GetGuildListResponse', '4': const {}},
    const {'1': 'GetGuild', '2': '.protocol.chat.v1.GetGuildRequest', '3': '.protocol.chat.v1.GetGuildResponse', '4': const {}},
    const {'1': 'GetGuildInvites', '2': '.protocol.chat.v1.GetGuildInvitesRequest', '3': '.protocol.chat.v1.GetGuildInvitesResponse', '4': const {}},
    const {'1': 'GetGuildMembers', '2': '.protocol.chat.v1.GetGuildMembersRequest', '3': '.protocol.chat.v1.GetGuildMembersResponse', '4': const {}},
    const {'1': 'GetGuildChannels', '2': '.protocol.chat.v1.GetGuildChannelsRequest', '3': '.protocol.chat.v1.GetGuildChannelsResponse', '4': const {}},
    const {'1': 'GetChannelMessages', '2': '.protocol.chat.v1.GetChannelMessagesRequest', '3': '.protocol.chat.v1.GetChannelMessagesResponse', '4': const {}},
    const {'1': 'GetMessage', '2': '.protocol.chat.v1.GetMessageRequest', '3': '.protocol.chat.v1.GetMessageResponse', '4': const {}},
    const {'1': 'UpdateGuildInformation', '2': '.protocol.chat.v1.UpdateGuildInformationRequest', '3': '.protocol.chat.v1.UpdateGuildInformationResponse', '4': const {}},
    const {'1': 'UpdateChannelInformation', '2': '.protocol.chat.v1.UpdateChannelInformationRequest', '3': '.protocol.chat.v1.UpdateChannelInformationResponse', '4': const {}},
    const {'1': 'UpdateChannelOrder', '2': '.protocol.chat.v1.UpdateChannelOrderRequest', '3': '.protocol.chat.v1.UpdateChannelOrderResponse', '4': const {}},
    const {'1': 'UpdateAllChannelOrder', '2': '.protocol.chat.v1.UpdateAllChannelOrderRequest', '3': '.protocol.chat.v1.UpdateAllChannelOrderResponse', '4': const {}},
    const {'1': 'UpdateMessageText', '2': '.protocol.chat.v1.UpdateMessageTextRequest', '3': '.protocol.chat.v1.UpdateMessageTextResponse', '4': const {}},
    const {'1': 'DeleteGuild', '2': '.protocol.chat.v1.DeleteGuildRequest', '3': '.protocol.chat.v1.DeleteGuildResponse', '4': const {}},
    const {'1': 'DeleteInvite', '2': '.protocol.chat.v1.DeleteInviteRequest', '3': '.protocol.chat.v1.DeleteInviteResponse', '4': const {}},
    const {'1': 'DeleteChannel', '2': '.protocol.chat.v1.DeleteChannelRequest', '3': '.protocol.chat.v1.DeleteChannelResponse', '4': const {}},
    const {'1': 'DeleteMessage', '2': '.protocol.chat.v1.DeleteMessageRequest', '3': '.protocol.chat.v1.DeleteMessageResponse', '4': const {}},
    const {'1': 'JoinGuild', '2': '.protocol.chat.v1.JoinGuildRequest', '3': '.protocol.chat.v1.JoinGuildResponse', '4': const {}},
    const {'1': 'LeaveGuild', '2': '.protocol.chat.v1.LeaveGuildRequest', '3': '.protocol.chat.v1.LeaveGuildResponse', '4': const {}},
    const {'1': 'TriggerAction', '2': '.protocol.chat.v1.TriggerActionRequest', '3': '.protocol.chat.v1.TriggerActionResponse', '4': const {}},
    const {'1': 'SendMessage', '2': '.protocol.chat.v1.SendMessageRequest', '3': '.protocol.chat.v1.SendMessageResponse', '4': const {}},
    const {'1': 'QueryHasPermission', '2': '.protocol.chat.v1.QueryHasPermissionRequest', '3': '.protocol.chat.v1.QueryHasPermissionResponse', '4': const {}},
    const {'1': 'SetPermissions', '2': '.protocol.chat.v1.SetPermissionsRequest', '3': '.protocol.chat.v1.SetPermissionsResponse', '4': const {}},
    const {'1': 'GetPermissions', '2': '.protocol.chat.v1.GetPermissionsRequest', '3': '.protocol.chat.v1.GetPermissionsResponse', '4': const {}},
    const {'1': 'MoveRole', '2': '.protocol.chat.v1.MoveRoleRequest', '3': '.protocol.chat.v1.MoveRoleResponse', '4': const {}},
    const {'1': 'GetGuildRoles', '2': '.protocol.chat.v1.GetGuildRolesRequest', '3': '.protocol.chat.v1.GetGuildRolesResponse', '4': const {}},
    const {'1': 'AddGuildRole', '2': '.protocol.chat.v1.AddGuildRoleRequest', '3': '.protocol.chat.v1.AddGuildRoleResponse', '4': const {}},
    const {'1': 'ModifyGuildRole', '2': '.protocol.chat.v1.ModifyGuildRoleRequest', '3': '.protocol.chat.v1.ModifyGuildRoleResponse', '4': const {}},
    const {'1': 'DeleteGuildRole', '2': '.protocol.chat.v1.DeleteGuildRoleRequest', '3': '.protocol.chat.v1.DeleteGuildRoleResponse', '4': const {}},
    const {'1': 'ManageUserRoles', '2': '.protocol.chat.v1.ManageUserRolesRequest', '3': '.protocol.chat.v1.ManageUserRolesResponse', '4': const {}},
    const {'1': 'GetUserRoles', '2': '.protocol.chat.v1.GetUserRolesRequest', '3': '.protocol.chat.v1.GetUserRolesResponse', '4': const {}},
    const {'1': 'Typing', '2': '.protocol.chat.v1.TypingRequest', '3': '.protocol.chat.v1.TypingResponse', '4': const {}},
    const {'1': 'PreviewGuild', '2': '.protocol.chat.v1.PreviewGuildRequest', '3': '.protocol.chat.v1.PreviewGuildResponse', '4': const {}},
    const {'1': 'GetBannedUsers', '2': '.protocol.chat.v1.GetBannedUsersRequest', '3': '.protocol.chat.v1.GetBannedUsersResponse', '4': const {}},
    const {'1': 'BanUser', '2': '.protocol.chat.v1.BanUserRequest', '3': '.protocol.chat.v1.BanUserResponse', '4': const {}},
    const {'1': 'KickUser', '2': '.protocol.chat.v1.KickUserRequest', '3': '.protocol.chat.v1.KickUserResponse', '4': const {}},
    const {'1': 'UnbanUser', '2': '.protocol.chat.v1.UnbanUserRequest', '3': '.protocol.chat.v1.UnbanUserResponse', '4': const {}},
    const {'1': 'GetPinnedMessages', '2': '.protocol.chat.v1.GetPinnedMessagesRequest', '3': '.protocol.chat.v1.GetPinnedMessagesResponse', '4': const {}},
    const {'1': 'PinMessage', '2': '.protocol.chat.v1.PinMessageRequest', '3': '.protocol.chat.v1.PinMessageResponse', '4': const {}},
    const {'1': 'UnpinMessage', '2': '.protocol.chat.v1.UnpinMessageRequest', '3': '.protocol.chat.v1.UnpinMessageResponse', '4': const {}},
    const {'1': 'StreamEvents', '2': '.protocol.chat.v1.StreamEventsRequest', '3': '.protocol.chat.v1.StreamEventsResponse', '4': const {}, '5': true, '6': true},
    const {'1': 'AddReaction', '2': '.protocol.chat.v1.AddReactionRequest', '3': '.protocol.chat.v1.AddReactionResponse', '4': const {}},
    const {'1': 'RemoveReaction', '2': '.protocol.chat.v1.RemoveReactionRequest', '3': '.protocol.chat.v1.RemoveReactionResponse', '4': const {}},
  ],
};

@$core.Deprecated('Use chatServiceDescriptor instead')
const $core.Map<$core.String, $core.Map<$core.String, $core.dynamic>> ChatServiceBase$messageJson = const {
  '.protocol.chat.v1.CreateGuildRequest': $7.CreateGuildRequest$json,
  '.protocol.harmonytypes.v1.Metadata': $0.Metadata$json,
  '.protocol.harmonytypes.v1.Metadata.ExtensionEntry': $0.Metadata_ExtensionEntry$json,
  '.protocol.harmonytypes.v1.Anything': $0.Anything$json,
  '.protocol.chat.v1.CreateGuildResponse': $7.CreateGuildResponse$json,
  '.protocol.chat.v1.CreateInviteRequest': $7.CreateInviteRequest$json,
  '.protocol.chat.v1.CreateInviteResponse': $7.CreateInviteResponse$json,
  '.protocol.chat.v1.CreateChannelRequest': $6.CreateChannelRequest$json,
  '.protocol.harmonytypes.v1.ItemPosition': $0.ItemPosition$json,
  '.protocol.chat.v1.CreateChannelResponse': $6.CreateChannelResponse$json,
  '.protocol.chat.v1.GetGuildListRequest': $7.GetGuildListRequest$json,
  '.protocol.chat.v1.GetGuildListResponse': $7.GetGuildListResponse$json,
  '.protocol.chat.v1.GuildListEntry': $7.GuildListEntry$json,
  '.protocol.chat.v1.GetGuildRequest': $7.GetGuildRequest$json,
  '.protocol.chat.v1.GetGuildResponse': $7.GetGuildResponse$json,
  '.protocol.chat.v1.Guild': $7.Guild$json,
  '.protocol.chat.v1.GetGuildInvitesRequest': $7.GetGuildInvitesRequest$json,
  '.protocol.chat.v1.GetGuildInvitesResponse': $7.GetGuildInvitesResponse$json,
  '.protocol.chat.v1.InviteWithId': $7.InviteWithId$json,
  '.protocol.chat.v1.Invite': $7.Invite$json,
  '.protocol.chat.v1.GetGuildMembersRequest': $7.GetGuildMembersRequest$json,
  '.protocol.chat.v1.GetGuildMembersResponse': $7.GetGuildMembersResponse$json,
  '.protocol.chat.v1.GetGuildChannelsRequest': $6.GetGuildChannelsRequest$json,
  '.protocol.chat.v1.GetGuildChannelsResponse': $6.GetGuildChannelsResponse$json,
  '.protocol.chat.v1.ChannelWithId': $6.ChannelWithId$json,
  '.protocol.chat.v1.Channel': $6.Channel$json,
  '.protocol.chat.v1.GetChannelMessagesRequest': $4.GetChannelMessagesRequest$json,
  '.protocol.chat.v1.GetChannelMessagesResponse': $4.GetChannelMessagesResponse$json,
  '.protocol.chat.v1.MessageWithId': $4.MessageWithId$json,
  '.protocol.chat.v1.Message': $4.Message$json,
  '.protocol.chat.v1.Overrides': $4.Overrides$json,
  '.protocol.harmonytypes.v1.Empty': $0.Empty$json,
  '.protocol.chat.v1.Content': $4.Content$json,
  '.protocol.chat.v1.Content.TextContent': $4.Content_TextContent$json,
  '.protocol.chat.v1.FormattedText': $4.FormattedText$json,
  '.protocol.chat.v1.Format': $4.Format$json,
  '.protocol.chat.v1.Format.Bold': $4.Format_Bold$json,
  '.protocol.chat.v1.Format.Italic': $4.Format_Italic$json,
  '.protocol.chat.v1.Format.Underline': $4.Format_Underline$json,
  '.protocol.chat.v1.Format.Monospace': $4.Format_Monospace$json,
  '.protocol.chat.v1.Format.Superscript': $4.Format_Superscript$json,
  '.protocol.chat.v1.Format.Subscript': $4.Format_Subscript$json,
  '.protocol.chat.v1.Format.CodeBlock': $4.Format_CodeBlock$json,
  '.protocol.chat.v1.Format.UserMention': $4.Format_UserMention$json,
  '.protocol.chat.v1.Format.RoleMention': $4.Format_RoleMention$json,
  '.protocol.chat.v1.Format.ChannelMention': $4.Format_ChannelMention$json,
  '.protocol.chat.v1.Format.GuildMention': $4.Format_GuildMention$json,
  '.protocol.chat.v1.Format.Emoji': $4.Format_Emoji$json,
  '.protocol.chat.v1.Format.Color': $4.Format_Color$json,
  '.protocol.chat.v1.Content.EmbedContent': $4.Content_EmbedContent$json,
  '.protocol.chat.v1.Embed': $4.Embed$json,
  '.protocol.chat.v1.Embed.EmbedHeading': $4.Embed_EmbedHeading$json,
  '.protocol.chat.v1.Embed.EmbedField': $4.Embed_EmbedField$json,
  '.protocol.chat.v1.Action': $4.Action$json,
  '.protocol.chat.v1.Action.Button': $4.Action_Button$json,
  '.protocol.chat.v1.Action.Dropdown': $4.Action_Dropdown$json,
  '.protocol.chat.v1.Action.Dropdown.Entry': $4.Action_Dropdown_Entry$json,
  '.protocol.chat.v1.Action.Input': $4.Action_Input$json,
  '.protocol.chat.v1.Content.AttachmentContent': $4.Content_AttachmentContent$json,
  '.protocol.chat.v1.Attachment': $4.Attachment$json,
  '.protocol.chat.v1.Content.PhotoContent': $4.Content_PhotoContent$json,
  '.protocol.chat.v1.Photo': $4.Photo$json,
  '.protocol.chat.v1.Minithumbnail': $4.Minithumbnail$json,
  '.protocol.chat.v1.Reaction': $4.Reaction$json,
  '.protocol.emote.v1.Emote': $1.Emote$json,
  '.protocol.chat.v1.GetMessageRequest': $4.GetMessageRequest$json,
  '.protocol.chat.v1.GetMessageResponse': $4.GetMessageResponse$json,
  '.protocol.chat.v1.UpdateGuildInformationRequest': $7.UpdateGuildInformationRequest$json,
  '.protocol.chat.v1.UpdateGuildInformationResponse': $7.UpdateGuildInformationResponse$json,
  '.protocol.chat.v1.UpdateChannelInformationRequest': $6.UpdateChannelInformationRequest$json,
  '.protocol.chat.v1.UpdateChannelInformationResponse': $6.UpdateChannelInformationResponse$json,
  '.protocol.chat.v1.UpdateChannelOrderRequest': $6.UpdateChannelOrderRequest$json,
  '.protocol.chat.v1.UpdateChannelOrderResponse': $6.UpdateChannelOrderResponse$json,
  '.protocol.chat.v1.UpdateAllChannelOrderRequest': $6.UpdateAllChannelOrderRequest$json,
  '.protocol.chat.v1.UpdateAllChannelOrderResponse': $6.UpdateAllChannelOrderResponse$json,
  '.protocol.chat.v1.UpdateMessageTextRequest': $4.UpdateMessageTextRequest$json,
  '.protocol.chat.v1.UpdateMessageTextResponse': $4.UpdateMessageTextResponse$json,
  '.protocol.chat.v1.DeleteGuildRequest': $7.DeleteGuildRequest$json,
  '.protocol.chat.v1.DeleteGuildResponse': $7.DeleteGuildResponse$json,
  '.protocol.chat.v1.DeleteInviteRequest': $7.DeleteInviteRequest$json,
  '.protocol.chat.v1.DeleteInviteResponse': $7.DeleteInviteResponse$json,
  '.protocol.chat.v1.DeleteChannelRequest': $6.DeleteChannelRequest$json,
  '.protocol.chat.v1.DeleteChannelResponse': $6.DeleteChannelResponse$json,
  '.protocol.chat.v1.DeleteMessageRequest': $4.DeleteMessageRequest$json,
  '.protocol.chat.v1.DeleteMessageResponse': $4.DeleteMessageResponse$json,
  '.protocol.chat.v1.JoinGuildRequest': $7.JoinGuildRequest$json,
  '.protocol.chat.v1.JoinGuildResponse': $7.JoinGuildResponse$json,
  '.protocol.chat.v1.LeaveGuildRequest': $7.LeaveGuildRequest$json,
  '.protocol.chat.v1.LeaveGuildResponse': $7.LeaveGuildResponse$json,
  '.protocol.chat.v1.TriggerActionRequest': $4.TriggerActionRequest$json,
  '.protocol.chat.v1.ActionPayload': $4.ActionPayload$json,
  '.protocol.chat.v1.ActionPayload.Button': $4.ActionPayload_Button$json,
  '.protocol.chat.v1.ActionPayload.Dropdown': $4.ActionPayload_Dropdown$json,
  '.protocol.chat.v1.ActionPayload.Input': $4.ActionPayload_Input$json,
  '.protocol.chat.v1.TriggerActionResponse': $4.TriggerActionResponse$json,
  '.protocol.chat.v1.SendMessageRequest': $4.SendMessageRequest$json,
  '.protocol.chat.v1.SendMessageResponse': $4.SendMessageResponse$json,
  '.protocol.chat.v1.QueryHasPermissionRequest': $5.QueryHasPermissionRequest$json,
  '.protocol.chat.v1.QueryHasPermissionResponse': $5.QueryHasPermissionResponse$json,
  '.protocol.chat.v1.SetPermissionsRequest': $5.SetPermissionsRequest$json,
  '.protocol.chat.v1.Permission': $5.Permission$json,
  '.protocol.chat.v1.SetPermissionsResponse': $5.SetPermissionsResponse$json,
  '.protocol.chat.v1.GetPermissionsRequest': $5.GetPermissionsRequest$json,
  '.protocol.chat.v1.GetPermissionsResponse': $5.GetPermissionsResponse$json,
  '.protocol.chat.v1.MoveRoleRequest': $5.MoveRoleRequest$json,
  '.protocol.chat.v1.MoveRoleResponse': $5.MoveRoleResponse$json,
  '.protocol.chat.v1.GetGuildRolesRequest': $5.GetGuildRolesRequest$json,
  '.protocol.chat.v1.GetGuildRolesResponse': $5.GetGuildRolesResponse$json,
  '.protocol.chat.v1.RoleWithId': $5.RoleWithId$json,
  '.protocol.chat.v1.Role': $5.Role$json,
  '.protocol.chat.v1.AddGuildRoleRequest': $5.AddGuildRoleRequest$json,
  '.protocol.chat.v1.AddGuildRoleResponse': $5.AddGuildRoleResponse$json,
  '.protocol.chat.v1.ModifyGuildRoleRequest': $5.ModifyGuildRoleRequest$json,
  '.protocol.chat.v1.ModifyGuildRoleResponse': $5.ModifyGuildRoleResponse$json,
  '.protocol.chat.v1.DeleteGuildRoleRequest': $5.DeleteGuildRoleRequest$json,
  '.protocol.chat.v1.DeleteGuildRoleResponse': $5.DeleteGuildRoleResponse$json,
  '.protocol.chat.v1.ManageUserRolesRequest': $5.ManageUserRolesRequest$json,
  '.protocol.chat.v1.ManageUserRolesResponse': $5.ManageUserRolesResponse$json,
  '.protocol.chat.v1.GetUserRolesRequest': $5.GetUserRolesRequest$json,
  '.protocol.chat.v1.GetUserRolesResponse': $5.GetUserRolesResponse$json,
  '.protocol.chat.v1.TypingRequest': $6.TypingRequest$json,
  '.protocol.chat.v1.TypingResponse': $6.TypingResponse$json,
  '.protocol.chat.v1.PreviewGuildRequest': $7.PreviewGuildRequest$json,
  '.protocol.chat.v1.PreviewGuildResponse': $7.PreviewGuildResponse$json,
  '.protocol.chat.v1.GetBannedUsersRequest': $7.GetBannedUsersRequest$json,
  '.protocol.chat.v1.GetBannedUsersResponse': $7.GetBannedUsersResponse$json,
  '.protocol.chat.v1.BanUserRequest': $7.BanUserRequest$json,
  '.protocol.chat.v1.BanUserResponse': $7.BanUserResponse$json,
  '.protocol.chat.v1.KickUserRequest': $7.KickUserRequest$json,
  '.protocol.chat.v1.KickUserResponse': $7.KickUserResponse$json,
  '.protocol.chat.v1.UnbanUserRequest': $7.UnbanUserRequest$json,
  '.protocol.chat.v1.UnbanUserResponse': $7.UnbanUserResponse$json,
  '.protocol.chat.v1.GetPinnedMessagesRequest': $4.GetPinnedMessagesRequest$json,
  '.protocol.chat.v1.GetPinnedMessagesResponse': $4.GetPinnedMessagesResponse$json,
  '.protocol.chat.v1.PinMessageRequest': $4.PinMessageRequest$json,
  '.protocol.chat.v1.PinMessageResponse': $4.PinMessageResponse$json,
  '.protocol.chat.v1.UnpinMessageRequest': $4.UnpinMessageRequest$json,
  '.protocol.chat.v1.UnpinMessageResponse': $4.UnpinMessageResponse$json,
  '.protocol.chat.v1.StreamEventsRequest': $8.StreamEventsRequest$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToGuild': $8.StreamEventsRequest_SubscribeToGuild$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToActions': $8.StreamEventsRequest_SubscribeToActions$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToHomeserverEvents': $8.StreamEventsRequest_SubscribeToHomeserverEvents$json,
  '.protocol.chat.v1.StreamEventsResponse': $8.StreamEventsResponse$json,
  '.protocol.chat.v1.StreamEvent': $8.StreamEvent$json,
  '.protocol.chat.v1.StreamEvent.GuildAddedToList': $8.StreamEvent_GuildAddedToList$json,
  '.protocol.chat.v1.StreamEvent.GuildRemovedFromList': $8.StreamEvent_GuildRemovedFromList$json,
  '.protocol.chat.v1.StreamEvent.ActionPerformed': $8.StreamEvent_ActionPerformed$json,
  '.protocol.chat.v1.StreamEvent.MessageSent': $8.StreamEvent_MessageSent$json,
  '.protocol.chat.v1.StreamEvent.MessageUpdated': $8.StreamEvent_MessageUpdated$json,
  '.protocol.chat.v1.StreamEvent.MessageDeleted': $8.StreamEvent_MessageDeleted$json,
  '.protocol.chat.v1.StreamEvent.ChannelCreated': $8.StreamEvent_ChannelCreated$json,
  '.protocol.chat.v1.StreamEvent.ChannelUpdated': $8.StreamEvent_ChannelUpdated$json,
  '.protocol.chat.v1.StreamEvent.ChannelDeleted': $8.StreamEvent_ChannelDeleted$json,
  '.protocol.chat.v1.StreamEvent.GuildUpdated': $8.StreamEvent_GuildUpdated$json,
  '.protocol.chat.v1.StreamEvent.GuildDeleted': $8.StreamEvent_GuildDeleted$json,
  '.protocol.chat.v1.StreamEvent.MemberJoined': $8.StreamEvent_MemberJoined$json,
  '.protocol.chat.v1.StreamEvent.MemberLeft': $8.StreamEvent_MemberLeft$json,
  '.protocol.chat.v1.StreamEvent.Typing': $8.StreamEvent_Typing$json,
  '.protocol.chat.v1.StreamEvent.RoleCreated': $8.StreamEvent_RoleCreated$json,
  '.protocol.chat.v1.StreamEvent.RoleDeleted': $8.StreamEvent_RoleDeleted$json,
  '.protocol.chat.v1.StreamEvent.RoleMoved': $8.StreamEvent_RoleMoved$json,
  '.protocol.chat.v1.StreamEvent.RoleUpdated': $8.StreamEvent_RoleUpdated$json,
  '.protocol.chat.v1.StreamEvent.RolePermissionsUpdated': $8.StreamEvent_RolePermissionsUpdated$json,
  '.protocol.chat.v1.StreamEvent.UserRolesUpdated': $8.StreamEvent_UserRolesUpdated$json,
  '.protocol.chat.v1.StreamEvent.PermissionUpdated': $8.StreamEvent_PermissionUpdated$json,
  '.protocol.chat.v1.StreamEvent.ChannelsReordered': $8.StreamEvent_ChannelsReordered$json,
  '.protocol.chat.v1.StreamEvent.ChannelPositionUpdated': $8.StreamEvent_ChannelPositionUpdated$json,
  '.protocol.chat.v1.StreamEvent.MessagePinned': $8.StreamEvent_MessagePinned$json,
  '.protocol.chat.v1.StreamEvent.MessageUnpinned': $8.StreamEvent_MessageUnpinned$json,
  '.protocol.chat.v1.StreamEvent.ReactionUpdated': $8.StreamEvent_ReactionUpdated$json,
  '.protocol.emote.v1.StreamEvent': $2.StreamEvent$json,
  '.protocol.emote.v1.EmotePackAdded': $2.EmotePackAdded$json,
  '.protocol.emote.v1.EmotePack': $1.EmotePack$json,
  '.protocol.emote.v1.EmotePackUpdated': $2.EmotePackUpdated$json,
  '.protocol.emote.v1.EmotePackDeleted': $2.EmotePackDeleted$json,
  '.protocol.emote.v1.EmotePackEmotesUpdated': $2.EmotePackEmotesUpdated$json,
  '.protocol.profile.v1.StreamEvent': $3.StreamEvent$json,
  '.protocol.profile.v1.ProfileUpdated': $3.ProfileUpdated$json,
  '.protocol.chat.v1.AddReactionRequest': $4.AddReactionRequest$json,
  '.protocol.chat.v1.AddReactionResponse': $4.AddReactionResponse$json,
  '.protocol.chat.v1.RemoveReactionRequest': $4.RemoveReactionRequest$json,
  '.protocol.chat.v1.RemoveReactionResponse': $4.RemoveReactionResponse$json,
};

/// Descriptor for `ChatService`. Decode as a `google.protobuf.ServiceDescriptorProto`.
final $typed_data.Uint8List chatServiceDescriptor = $convert.base64Decode('CgtDaGF0U2VydmljZRJmCgtDcmVhdGVHdWlsZBIkLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlR3VpbGRSZXF1ZXN0GiUucHJvdG9jb2wuY2hhdC52MS5DcmVhdGVHdWlsZFJlc3BvbnNlIgqaRAIIAZpEAhoAEn4KDENyZWF0ZUludml0ZRIlLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlSW52aXRlUmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlSW52aXRlUmVzcG9uc2UiH5pEAggBmkQXGhVpbnZpdGVzLm1hbmFnZS5jcmVhdGUSggEKDUNyZWF0ZUNoYW5uZWwSJi5wcm90b2NvbC5jaGF0LnYxLkNyZWF0ZUNoYW5uZWxSZXF1ZXN0GicucHJvdG9jb2wuY2hhdC52MS5DcmVhdGVDaGFubmVsUmVzcG9uc2UiIJpEAggBmkQYGhZjaGFubmVscy5tYW5hZ2UuY3JlYXRlEmQKDEdldEd1aWxkTGlzdBIlLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRMaXN0UmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRMaXN0UmVzcG9uc2UiBZpEAggBElgKCEdldEd1aWxkEiEucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZFJlcXVlc3QaIi5wcm90b2NvbC5jaGF0LnYxLkdldEd1aWxkUmVzcG9uc2UiBZpEAggBEn4KD0dldEd1aWxkSW52aXRlcxIoLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRJbnZpdGVzUmVxdWVzdBopLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRJbnZpdGVzUmVzcG9uc2UiFppEAggBmkQOGgxpbnZpdGVzLnZpZXcSbQoPR2V0R3VpbGRNZW1iZXJzEigucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZE1lbWJlcnNSZXF1ZXN0GikucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZE1lbWJlcnNSZXNwb25zZSIFmkQCCAEScAoQR2V0R3VpbGRDaGFubmVscxIpLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRDaGFubmVsc1JlcXVlc3QaKi5wcm90b2NvbC5jaGF0LnYxLkdldEd1aWxkQ2hhbm5lbHNSZXNwb25zZSIFmkQCCAESiAEKEkdldENoYW5uZWxNZXNzYWdlcxIrLnByb3RvY29sLmNoYXQudjEuR2V0Q2hhbm5lbE1lc3NhZ2VzUmVxdWVzdBosLnByb3RvY29sLmNoYXQudjEuR2V0Q2hhbm5lbE1lc3NhZ2VzUmVzcG9uc2UiF5pEAggBmkQPGg1tZXNzYWdlcy52aWV3EnAKCkdldE1lc3NhZ2USIy5wcm90b2NvbC5jaGF0LnYxLkdldE1lc3NhZ2VSZXF1ZXN0GiQucHJvdG9jb2wuY2hhdC52MS5HZXRNZXNzYWdlUmVzcG9uc2UiF5pEAggBmkQPGg1tZXNzYWdlcy52aWV3EqYBChZVcGRhdGVHdWlsZEluZm9ybWF0aW9uEi8ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVHdWlsZEluZm9ybWF0aW9uUmVxdWVzdBowLnByb3RvY29sLmNoYXQudjEuVXBkYXRlR3VpbGRJbmZvcm1hdGlvblJlc3BvbnNlIimaRAIIAZpEIRofZ3VpbGQubWFuYWdlLmNoYW5nZS1pbmZvcm1hdGlvbhKvAQoYVXBkYXRlQ2hhbm5lbEluZm9ybWF0aW9uEjEucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVDaGFubmVsSW5mb3JtYXRpb25SZXF1ZXN0GjIucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVDaGFubmVsSW5mb3JtYXRpb25SZXNwb25zZSIsmkQCCAGaRCQaImNoYW5uZWxzLm1hbmFnZS5jaGFuZ2UtaW5mb3JtYXRpb24SjwEKElVwZGF0ZUNoYW5uZWxPcmRlchIrLnByb3RvY29sLmNoYXQudjEuVXBkYXRlQ2hhbm5lbE9yZGVyUmVxdWVzdBosLnByb3RvY29sLmNoYXQudjEuVXBkYXRlQ2hhbm5lbE9yZGVyUmVzcG9uc2UiHppEAggBmkQWGhRjaGFubmVscy5tYW5hZ2UubW92ZRKYAQoVVXBkYXRlQWxsQ2hhbm5lbE9yZGVyEi4ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVBbGxDaGFubmVsT3JkZXJSZXF1ZXN0Gi8ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVBbGxDaGFubmVsT3JkZXJSZXNwb25zZSIemkQCCAGaRBYaFGNoYW5uZWxzLm1hbmFnZS5tb3ZlEoUBChFVcGRhdGVNZXNzYWdlVGV4dBIqLnByb3RvY29sLmNoYXQudjEuVXBkYXRlTWVzc2FnZVRleHRSZXF1ZXN0GisucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVNZXNzYWdlVGV4dFJlc3BvbnNlIheaRAIIAZpEDxoNbWVzc2FnZXMuc2VuZBJ5CgtEZWxldGVHdWlsZBIkLnByb3RvY29sLmNoYXQudjEuRGVsZXRlR3VpbGRSZXF1ZXN0GiUucHJvdG9jb2wuY2hhdC52MS5EZWxldGVHdWlsZFJlc3BvbnNlIh2aRAIIAZpEFRoTZ3VpbGQubWFuYWdlLmRlbGV0ZRJ+CgxEZWxldGVJbnZpdGUSJS5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZUludml0ZVJlcXVlc3QaJi5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZUludml0ZVJlc3BvbnNlIh+aRAIIAZpEFxoVaW52aXRlcy5tYW5hZ2UuZGVsZXRlEoIBCg1EZWxldGVDaGFubmVsEiYucHJvdG9jb2wuY2hhdC52MS5EZWxldGVDaGFubmVsUmVxdWVzdBonLnByb3RvY29sLmNoYXQudjEuRGVsZXRlQ2hhbm5lbFJlc3BvbnNlIiCaRAIIAZpEGBoWY2hhbm5lbHMubWFuYWdlLmRlbGV0ZRJnCg1EZWxldGVNZXNzYWdlEiYucHJvdG9jb2wuY2hhdC52MS5EZWxldGVNZXNzYWdlUmVxdWVzdBonLnByb3RvY29sLmNoYXQudjEuRGVsZXRlTWVzc2FnZVJlc3BvbnNlIgWaRAIIARJbCglKb2luR3VpbGQSIi5wcm90b2NvbC5jaGF0LnYxLkpvaW5HdWlsZFJlcXVlc3QaIy5wcm90b2NvbC5jaGF0LnYxLkpvaW5HdWlsZFJlc3BvbnNlIgWaRAIIARJeCgpMZWF2ZUd1aWxkEiMucHJvdG9jb2wuY2hhdC52MS5MZWF2ZUd1aWxkUmVxdWVzdBokLnByb3RvY29sLmNoYXQudjEuTGVhdmVHdWlsZFJlc3BvbnNlIgWaRAIIARJ7Cg1UcmlnZ2VyQWN0aW9uEiYucHJvdG9jb2wuY2hhdC52MS5UcmlnZ2VyQWN0aW9uUmVxdWVzdBonLnByb3RvY29sLmNoYXQudjEuVHJpZ2dlckFjdGlvblJlc3BvbnNlIhmaRAIIAZpEERoPYWN0aW9ucy50cmlnZ2VyEnMKC1NlbmRNZXNzYWdlEiQucHJvdG9jb2wuY2hhdC52MS5TZW5kTWVzc2FnZVJlcXVlc3QaJS5wcm90b2NvbC5jaGF0LnYxLlNlbmRNZXNzYWdlUmVzcG9uc2UiF5pEAggBmkQPGg1tZXNzYWdlcy5zZW5kEnYKElF1ZXJ5SGFzUGVybWlzc2lvbhIrLnByb3RvY29sLmNoYXQudjEuUXVlcnlIYXNQZXJtaXNzaW9uUmVxdWVzdBosLnByb3RvY29sLmNoYXQudjEuUXVlcnlIYXNQZXJtaXNzaW9uUmVzcG9uc2UiBZpEAggBEoUBCg5TZXRQZXJtaXNzaW9ucxInLnByb3RvY29sLmNoYXQudjEuU2V0UGVybWlzc2lvbnNSZXF1ZXN0GigucHJvdG9jb2wuY2hhdC52MS5TZXRQZXJtaXNzaW9uc1Jlc3BvbnNlIiCaRAIIAZpEGBoWcGVybWlzc2lvbnMubWFuYWdlLnNldBKFAQoOR2V0UGVybWlzc2lvbnMSJy5wcm90b2NvbC5jaGF0LnYxLkdldFBlcm1pc3Npb25zUmVxdWVzdBooLnByb3RvY29sLmNoYXQudjEuR2V0UGVybWlzc2lvbnNSZXNwb25zZSIgmkQCCAGaRBgaFnBlcm1pc3Npb25zLm1hbmFnZS5nZXQSaQoITW92ZVJvbGUSIS5wcm90b2NvbC5jaGF0LnYxLk1vdmVSb2xlUmVxdWVzdBoiLnByb3RvY29sLmNoYXQudjEuTW92ZVJvbGVSZXNwb25zZSIWmkQCCAGaRA4aDHJvbGVzLm1hbmFnZRJ1Cg1HZXRHdWlsZFJvbGVzEiYucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZFJvbGVzUmVxdWVzdBonLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRSb2xlc1Jlc3BvbnNlIhOaRAIIAZpECxoJcm9sZXMuZ2V0EnUKDEFkZEd1aWxkUm9sZRIlLnByb3RvY29sLmNoYXQudjEuQWRkR3VpbGRSb2xlUmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuQWRkR3VpbGRSb2xlUmVzcG9uc2UiFppEAggBmkQOGgxyb2xlcy5tYW5hZ2USfgoPTW9kaWZ5R3VpbGRSb2xlEigucHJvdG9jb2wuY2hhdC52MS5Nb2RpZnlHdWlsZFJvbGVSZXF1ZXN0GikucHJvdG9jb2wuY2hhdC52MS5Nb2RpZnlHdWlsZFJvbGVSZXNwb25zZSIWmkQCCAGaRA4aDHJvbGVzLm1hbmFnZRJ+Cg9EZWxldGVHdWlsZFJvbGUSKC5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZUd1aWxkUm9sZVJlcXVlc3QaKS5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZUd1aWxkUm9sZVJlc3BvbnNlIhaaRAIIAZpEDhoMcm9sZXMubWFuYWdlEoMBCg9NYW5hZ2VVc2VyUm9sZXMSKC5wcm90b2NvbC5jaGF0LnYxLk1hbmFnZVVzZXJSb2xlc1JlcXVlc3QaKS5wcm90b2NvbC5jaGF0LnYxLk1hbmFnZVVzZXJSb2xlc1Jlc3BvbnNlIhuaRAIIAZpEExoRcm9sZXMudXNlci5tYW5hZ2USZAoMR2V0VXNlclJvbGVzEiUucHJvdG9jb2wuY2hhdC52MS5HZXRVc2VyUm9sZXNSZXF1ZXN0GiYucHJvdG9jb2wuY2hhdC52MS5HZXRVc2VyUm9sZXNSZXNwb25zZSIFmkQCCAESZAoGVHlwaW5nEh8ucHJvdG9jb2wuY2hhdC52MS5UeXBpbmdSZXF1ZXN0GiAucHJvdG9jb2wuY2hhdC52MS5UeXBpbmdSZXNwb25zZSIXmkQCCAGaRA8aDW1lc3NhZ2VzLnNlbmQSZAoMUHJldmlld0d1aWxkEiUucHJvdG9jb2wuY2hhdC52MS5QcmV2aWV3R3VpbGRSZXF1ZXN0GiYucHJvdG9jb2wuY2hhdC52MS5QcmV2aWV3R3VpbGRSZXNwb25zZSIFmkQCCAASjgEKDkdldEJhbm5lZFVzZXJzEicucHJvdG9jb2wuY2hhdC52MS5HZXRCYW5uZWRVc2Vyc1JlcXVlc3QaKC5wcm90b2NvbC5jaGF0LnYxLkdldEJhbm5lZFVzZXJzUmVzcG9uc2UiKZpEAggBmkQhGh9ndWlsZC5tYW5hZ2UuY2hhbmdlLWluZm9ybWF0aW9uEmkKB0JhblVzZXISIC5wcm90b2NvbC5jaGF0LnYxLkJhblVzZXJSZXF1ZXN0GiEucHJvdG9jb2wuY2hhdC52MS5CYW5Vc2VyUmVzcG9uc2UiGZpEAggBmkQRGg91c2VyLm1hbmFnZS5iYW4SbQoIS2lja1VzZXISIS5wcm90b2NvbC5jaGF0LnYxLktpY2tVc2VyUmVxdWVzdBoiLnByb3RvY29sLmNoYXQudjEuS2lja1VzZXJSZXNwb25zZSIamkQCCAGaRBIaEHVzZXIubWFuYWdlLmtpY2sScQoJVW5iYW5Vc2VyEiIucHJvdG9jb2wuY2hhdC52MS5VbmJhblVzZXJSZXF1ZXN0GiMucHJvdG9jb2wuY2hhdC52MS5VbmJhblVzZXJSZXNwb25zZSIbmkQCCAGaRBMaEXVzZXIubWFuYWdlLnVuYmFuEoUBChFHZXRQaW5uZWRNZXNzYWdlcxIqLnByb3RvY29sLmNoYXQudjEuR2V0UGlubmVkTWVzc2FnZXNSZXF1ZXN0GisucHJvdG9jb2wuY2hhdC52MS5HZXRQaW5uZWRNZXNzYWdlc1Jlc3BvbnNlIheaRAIIAZpEDxoNbWVzc2FnZXMudmlldxJ0CgpQaW5NZXNzYWdlEiMucHJvdG9jb2wuY2hhdC52MS5QaW5NZXNzYWdlUmVxdWVzdBokLnByb3RvY29sLmNoYXQudjEuUGluTWVzc2FnZVJlc3BvbnNlIhuaRAIIAZpEExoRbWVzc2FnZXMucGlucy5hZGQSfQoMVW5waW5NZXNzYWdlEiUucHJvdG9jb2wuY2hhdC52MS5VbnBpbk1lc3NhZ2VSZXF1ZXN0GiYucHJvdG9jb2wuY2hhdC52MS5VbnBpbk1lc3NhZ2VSZXNwb25zZSIemkQCCAGaRBYaFG1lc3NhZ2VzLnBpbnMucmVtb3ZlEmgKDFN0cmVhbUV2ZW50cxIlLnByb3RvY29sLmNoYXQudjEuU3RyZWFtRXZlbnRzUmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuU3RyZWFtRXZlbnRzUmVzcG9uc2UiBZpEAggBKAEwARJ8CgtBZGRSZWFjdGlvbhIkLnByb3RvY29sLmNoYXQudjEuQWRkUmVhY3Rpb25SZXF1ZXN0GiUucHJvdG9jb2wuY2hhdC52MS5BZGRSZWFjdGlvblJlc3BvbnNlIiCaRAIIAZpEGBoWbWVzc2FnZXMucmVhY3Rpb25zLmFkZBKIAQoOUmVtb3ZlUmVhY3Rpb24SJy5wcm90b2NvbC5jaGF0LnYxLlJlbW92ZVJlYWN0aW9uUmVxdWVzdBooLnByb3RvY29sLmNoYXQudjEuUmVtb3ZlUmVhY3Rpb25SZXNwb25zZSIjmkQCCAGaRBsaGW1lc3NhZ2VzLnJlYWN0aW9ucy5yZW1vdmU=');
