///
//  Generated code. Do not modify.
//  source: chat/v1/chat.proto
//
// @dart = 2.7
// ignore_for_file: annotate_overrides,camel_case_types,unnecessary_const,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type,unnecessary_this,prefer_final_fields

import 'guilds.pbjson.dart' as $2;
import '../../harmonytypes/v1/types.pbjson.dart' as $0;
import '../../google/protobuf/any.pbjson.dart' as $10;
import 'channels.pbjson.dart' as $3;
import 'emotes.pbjson.dart' as $4;
import 'messages.pbjson.dart' as $5;
import '../../google/protobuf/timestamp.pbjson.dart' as $1;
import '../../google/protobuf/empty.pbjson.dart' as $6;
import 'permissions.pbjson.dart' as $7;
import 'streaming.pbjson.dart' as $8;
import 'profile.pbjson.dart' as $9;

const ChatServiceBase$json = const {
  '1': 'ChatService',
  '2': const [
    const {'1': 'CreateGuild', '2': '.protocol.chat.v1.CreateGuildRequest', '3': '.protocol.chat.v1.CreateGuildResponse', '4': const {}},
    const {'1': 'CreateInvite', '2': '.protocol.chat.v1.CreateInviteRequest', '3': '.protocol.chat.v1.CreateInviteResponse', '4': const {}},
    const {'1': 'CreateChannel', '2': '.protocol.chat.v1.CreateChannelRequest', '3': '.protocol.chat.v1.CreateChannelResponse', '4': const {}},
    const {'1': 'CreateEmotePack', '2': '.protocol.chat.v1.CreateEmotePackRequest', '3': '.protocol.chat.v1.CreateEmotePackResponse', '4': const {}},
    const {'1': 'GetGuildList', '2': '.protocol.chat.v1.GetGuildListRequest', '3': '.protocol.chat.v1.GetGuildListResponse', '4': const {}},
    const {'1': 'AddGuildToGuildList', '2': '.protocol.chat.v1.AddGuildToGuildListRequest', '3': '.protocol.chat.v1.AddGuildToGuildListResponse', '4': const {}},
    const {'1': 'RemoveGuildFromGuildList', '2': '.protocol.chat.v1.RemoveGuildFromGuildListRequest', '3': '.protocol.chat.v1.RemoveGuildFromGuildListResponse', '4': const {}},
    const {'1': 'GetGuild', '2': '.protocol.chat.v1.GetGuildRequest', '3': '.protocol.chat.v1.GetGuildResponse', '4': const {}},
    const {'1': 'GetGuildInvites', '2': '.protocol.chat.v1.GetGuildInvitesRequest', '3': '.protocol.chat.v1.GetGuildInvitesResponse', '4': const {}},
    const {'1': 'GetGuildMembers', '2': '.protocol.chat.v1.GetGuildMembersRequest', '3': '.protocol.chat.v1.GetGuildMembersResponse', '4': const {}},
    const {'1': 'GetGuildChannels', '2': '.protocol.chat.v1.GetGuildChannelsRequest', '3': '.protocol.chat.v1.GetGuildChannelsResponse', '4': const {}},
    const {'1': 'GetChannelMessages', '2': '.protocol.chat.v1.GetChannelMessagesRequest', '3': '.protocol.chat.v1.GetChannelMessagesResponse', '4': const {}},
    const {'1': 'GetMessage', '2': '.protocol.chat.v1.GetMessageRequest', '3': '.protocol.chat.v1.GetMessageResponse', '4': const {}},
    const {'1': 'GetEmotePacks', '2': '.protocol.chat.v1.GetEmotePacksRequest', '3': '.protocol.chat.v1.GetEmotePacksResponse', '4': const {}},
    const {'1': 'GetEmotePackEmotes', '2': '.protocol.chat.v1.GetEmotePackEmotesRequest', '3': '.protocol.chat.v1.GetEmotePackEmotesResponse', '4': const {}},
    const {'1': 'UpdateGuildInformation', '2': '.protocol.chat.v1.UpdateGuildInformationRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'UpdateChannelInformation', '2': '.protocol.chat.v1.UpdateChannelInformationRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'UpdateChannelOrder', '2': '.protocol.chat.v1.UpdateChannelOrderRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'UpdateMessage', '2': '.protocol.chat.v1.UpdateMessageRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'AddEmoteToPack', '2': '.protocol.chat.v1.AddEmoteToPackRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteGuild', '2': '.protocol.chat.v1.DeleteGuildRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteInvite', '2': '.protocol.chat.v1.DeleteInviteRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteChannel', '2': '.protocol.chat.v1.DeleteChannelRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteMessage', '2': '.protocol.chat.v1.DeleteMessageRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteEmoteFromPack', '2': '.protocol.chat.v1.DeleteEmoteFromPackRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteEmotePack', '2': '.protocol.chat.v1.DeleteEmotePackRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DequipEmotePack', '2': '.protocol.chat.v1.DequipEmotePackRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'JoinGuild', '2': '.protocol.chat.v1.JoinGuildRequest', '3': '.protocol.chat.v1.JoinGuildResponse', '4': const {}},
    const {'1': 'LeaveGuild', '2': '.protocol.chat.v1.LeaveGuildRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'TriggerAction', '2': '.protocol.chat.v1.TriggerActionRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'SendMessage', '2': '.protocol.chat.v1.SendMessageRequest', '3': '.protocol.chat.v1.SendMessageResponse', '4': const {}},
    const {'1': 'QueryHasPermission', '2': '.protocol.chat.v1.QueryPermissionsRequest', '3': '.protocol.chat.v1.QueryPermissionsResponse', '4': const {}},
    const {'1': 'SetPermissions', '2': '.protocol.chat.v1.SetPermissionsRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'GetPermissions', '2': '.protocol.chat.v1.GetPermissionsRequest', '3': '.protocol.chat.v1.GetPermissionsResponse', '4': const {}},
    const {'1': 'MoveRole', '2': '.protocol.chat.v1.MoveRoleRequest', '3': '.protocol.chat.v1.MoveRoleResponse', '4': const {}},
    const {'1': 'GetGuildRoles', '2': '.protocol.chat.v1.GetGuildRolesRequest', '3': '.protocol.chat.v1.GetGuildRolesResponse', '4': const {}},
    const {'1': 'AddGuildRole', '2': '.protocol.chat.v1.AddGuildRoleRequest', '3': '.protocol.chat.v1.AddGuildRoleResponse', '4': const {}},
    const {'1': 'ModifyGuildRole', '2': '.protocol.chat.v1.ModifyGuildRoleRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'DeleteGuildRole', '2': '.protocol.chat.v1.DeleteGuildRoleRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'ManageUserRoles', '2': '.protocol.chat.v1.ManageUserRolesRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'GetUserRoles', '2': '.protocol.chat.v1.GetUserRolesRequest', '3': '.protocol.chat.v1.GetUserRolesResponse', '4': const {}},
    const {'1': 'StreamEvents', '2': '.protocol.chat.v1.StreamEventsRequest', '3': '.protocol.chat.v1.Event', '4': const {}, '5': true, '6': true},
    const {'1': 'GetUser', '2': '.protocol.chat.v1.GetUserRequest', '3': '.protocol.chat.v1.GetUserResponse', '4': const {}},
    const {'1': 'GetUserMetadata', '2': '.protocol.chat.v1.GetUserMetadataRequest', '3': '.protocol.chat.v1.GetUserMetadataResponse', '4': const {}},
    const {'1': 'ProfileUpdate', '2': '.protocol.chat.v1.ProfileUpdateRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'Typing', '2': '.protocol.chat.v1.TypingRequest', '3': '.google.protobuf.Empty', '4': const {}},
    const {'1': 'PreviewGuild', '2': '.protocol.chat.v1.PreviewGuildRequest', '3': '.protocol.chat.v1.PreviewGuildResponse'},
  ],
};

const ChatServiceBase$messageJson = const {
  '.protocol.chat.v1.CreateGuildRequest': $2.CreateGuildRequest$json,
  '.protocol.harmonytypes.v1.Metadata': $0.Metadata$json,
  '.protocol.harmonytypes.v1.Metadata.ExtensionEntry': $0.Metadata_ExtensionEntry$json,
  '.google.protobuf.Any': $10.Any$json,
  '.protocol.chat.v1.CreateGuildResponse': $2.CreateGuildResponse$json,
  '.protocol.chat.v1.CreateInviteRequest': $2.CreateInviteRequest$json,
  '.protocol.chat.v1.CreateInviteResponse': $2.CreateInviteResponse$json,
  '.protocol.chat.v1.CreateChannelRequest': $3.CreateChannelRequest$json,
  '.protocol.chat.v1.CreateChannelResponse': $3.CreateChannelResponse$json,
  '.protocol.chat.v1.CreateEmotePackRequest': $4.CreateEmotePackRequest$json,
  '.protocol.chat.v1.CreateEmotePackResponse': $4.CreateEmotePackResponse$json,
  '.protocol.chat.v1.GetGuildListRequest': $2.GetGuildListRequest$json,
  '.protocol.chat.v1.GetGuildListResponse': $2.GetGuildListResponse$json,
  '.protocol.chat.v1.GetGuildListResponse.GuildListEntry': $2.GetGuildListResponse_GuildListEntry$json,
  '.protocol.chat.v1.AddGuildToGuildListRequest': $2.AddGuildToGuildListRequest$json,
  '.protocol.chat.v1.AddGuildToGuildListResponse': $2.AddGuildToGuildListResponse$json,
  '.protocol.chat.v1.RemoveGuildFromGuildListRequest': $2.RemoveGuildFromGuildListRequest$json,
  '.protocol.chat.v1.RemoveGuildFromGuildListResponse': $2.RemoveGuildFromGuildListResponse$json,
  '.protocol.chat.v1.GetGuildRequest': $2.GetGuildRequest$json,
  '.protocol.chat.v1.GetGuildResponse': $2.GetGuildResponse$json,
  '.protocol.chat.v1.GetGuildInvitesRequest': $2.GetGuildInvitesRequest$json,
  '.protocol.chat.v1.GetGuildInvitesResponse': $2.GetGuildInvitesResponse$json,
  '.protocol.chat.v1.GetGuildInvitesResponse.Invite': $2.GetGuildInvitesResponse_Invite$json,
  '.protocol.chat.v1.GetGuildMembersRequest': $2.GetGuildMembersRequest$json,
  '.protocol.chat.v1.GetGuildMembersResponse': $2.GetGuildMembersResponse$json,
  '.protocol.chat.v1.GetGuildChannelsRequest': $3.GetGuildChannelsRequest$json,
  '.protocol.chat.v1.GetGuildChannelsResponse': $3.GetGuildChannelsResponse$json,
  '.protocol.chat.v1.GetGuildChannelsResponse.Channel': $3.GetGuildChannelsResponse_Channel$json,
  '.protocol.chat.v1.GetChannelMessagesRequest': $5.GetChannelMessagesRequest$json,
  '.protocol.chat.v1.GetChannelMessagesResponse': $5.GetChannelMessagesResponse$json,
  '.protocol.harmonytypes.v1.Message': $0.Message$json,
  '.google.protobuf.Timestamp': $1.Timestamp$json,
  '.protocol.harmonytypes.v1.Embed': $0.Embed$json,
  '.protocol.harmonytypes.v1.EmbedHeading': $0.EmbedHeading$json,
  '.protocol.harmonytypes.v1.EmbedField': $0.EmbedField$json,
  '.protocol.harmonytypes.v1.Action': $0.Action$json,
  '.protocol.harmonytypes.v1.Attachment': $0.Attachment$json,
  '.protocol.harmonytypes.v1.Override': $0.Override$json,
  '.google.protobuf.Empty': $6.Empty$json,
  '.protocol.chat.v1.GetMessageRequest': $5.GetMessageRequest$json,
  '.protocol.chat.v1.GetMessageResponse': $5.GetMessageResponse$json,
  '.protocol.chat.v1.GetEmotePacksRequest': $4.GetEmotePacksRequest$json,
  '.protocol.chat.v1.GetEmotePacksResponse': $4.GetEmotePacksResponse$json,
  '.protocol.chat.v1.GetEmotePacksResponse.EmotePack': $4.GetEmotePacksResponse_EmotePack$json,
  '.protocol.chat.v1.GetEmotePackEmotesRequest': $4.GetEmotePackEmotesRequest$json,
  '.protocol.chat.v1.GetEmotePackEmotesResponse': $4.GetEmotePackEmotesResponse$json,
  '.protocol.chat.v1.GetEmotePackEmotesResponse.Emote': $4.GetEmotePackEmotesResponse_Emote$json,
  '.protocol.chat.v1.UpdateGuildInformationRequest': $2.UpdateGuildInformationRequest$json,
  '.protocol.chat.v1.UpdateChannelInformationRequest': $3.UpdateChannelInformationRequest$json,
  '.protocol.chat.v1.UpdateChannelOrderRequest': $3.UpdateChannelOrderRequest$json,
  '.protocol.chat.v1.UpdateMessageRequest': $5.UpdateMessageRequest$json,
  '.protocol.chat.v1.AddEmoteToPackRequest': $4.AddEmoteToPackRequest$json,
  '.protocol.chat.v1.DeleteGuildRequest': $2.DeleteGuildRequest$json,
  '.protocol.chat.v1.DeleteInviteRequest': $2.DeleteInviteRequest$json,
  '.protocol.chat.v1.DeleteChannelRequest': $3.DeleteChannelRequest$json,
  '.protocol.chat.v1.DeleteMessageRequest': $5.DeleteMessageRequest$json,
  '.protocol.chat.v1.DeleteEmoteFromPackRequest': $4.DeleteEmoteFromPackRequest$json,
  '.protocol.chat.v1.DeleteEmotePackRequest': $4.DeleteEmotePackRequest$json,
  '.protocol.chat.v1.DequipEmotePackRequest': $4.DequipEmotePackRequest$json,
  '.protocol.chat.v1.JoinGuildRequest': $2.JoinGuildRequest$json,
  '.protocol.chat.v1.JoinGuildResponse': $2.JoinGuildResponse$json,
  '.protocol.chat.v1.LeaveGuildRequest': $2.LeaveGuildRequest$json,
  '.protocol.chat.v1.TriggerActionRequest': $5.TriggerActionRequest$json,
  '.protocol.chat.v1.SendMessageRequest': $5.SendMessageRequest$json,
  '.protocol.chat.v1.SendMessageResponse': $5.SendMessageResponse$json,
  '.protocol.chat.v1.QueryPermissionsRequest': $7.QueryPermissionsRequest$json,
  '.protocol.chat.v1.QueryPermissionsResponse': $7.QueryPermissionsResponse$json,
  '.protocol.chat.v1.SetPermissionsRequest': $7.SetPermissionsRequest$json,
  '.protocol.chat.v1.PermissionList': $7.PermissionList$json,
  '.protocol.chat.v1.Permission': $7.Permission$json,
  '.protocol.chat.v1.GetPermissionsRequest': $7.GetPermissionsRequest$json,
  '.protocol.chat.v1.GetPermissionsResponse': $7.GetPermissionsResponse$json,
  '.protocol.chat.v1.MoveRoleRequest': $7.MoveRoleRequest$json,
  '.protocol.chat.v1.MoveRoleResponse': $7.MoveRoleResponse$json,
  '.protocol.chat.v1.GetGuildRolesRequest': $7.GetGuildRolesRequest$json,
  '.protocol.chat.v1.GetGuildRolesResponse': $7.GetGuildRolesResponse$json,
  '.protocol.chat.v1.Role': $7.Role$json,
  '.protocol.chat.v1.AddGuildRoleRequest': $7.AddGuildRoleRequest$json,
  '.protocol.chat.v1.AddGuildRoleResponse': $7.AddGuildRoleResponse$json,
  '.protocol.chat.v1.ModifyGuildRoleRequest': $7.ModifyGuildRoleRequest$json,
  '.protocol.chat.v1.DeleteGuildRoleRequest': $7.DeleteGuildRoleRequest$json,
  '.protocol.chat.v1.ManageUserRolesRequest': $7.ManageUserRolesRequest$json,
  '.protocol.chat.v1.GetUserRolesRequest': $7.GetUserRolesRequest$json,
  '.protocol.chat.v1.GetUserRolesResponse': $7.GetUserRolesResponse$json,
  '.protocol.chat.v1.StreamEventsRequest': $8.StreamEventsRequest$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToGuild': $8.StreamEventsRequest_SubscribeToGuild$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToActions': $8.StreamEventsRequest_SubscribeToActions$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToHomeserverEvents': $8.StreamEventsRequest_SubscribeToHomeserverEvents$json,
  '.protocol.chat.v1.Event': $8.Event$json,
  '.protocol.chat.v1.Event.GuildAddedToList': $8.Event_GuildAddedToList$json,
  '.protocol.chat.v1.Event.GuildRemovedFromList': $8.Event_GuildRemovedFromList$json,
  '.protocol.chat.v1.Event.ActionPerformed': $8.Event_ActionPerformed$json,
  '.protocol.chat.v1.Event.MessageSent': $8.Event_MessageSent$json,
  '.protocol.chat.v1.Event.MessageUpdated': $8.Event_MessageUpdated$json,
  '.protocol.chat.v1.Event.MessageDeleted': $8.Event_MessageDeleted$json,
  '.protocol.chat.v1.Event.ChannelCreated': $8.Event_ChannelCreated$json,
  '.protocol.chat.v1.Event.ChannelUpdated': $8.Event_ChannelUpdated$json,
  '.protocol.chat.v1.Event.ChannelDeleted': $8.Event_ChannelDeleted$json,
  '.protocol.chat.v1.Event.GuildUpdated': $8.Event_GuildUpdated$json,
  '.protocol.chat.v1.Event.GuildDeleted': $8.Event_GuildDeleted$json,
  '.protocol.chat.v1.Event.MemberJoined': $8.Event_MemberJoined$json,
  '.protocol.chat.v1.Event.MemberLeft': $8.Event_MemberLeft$json,
  '.protocol.chat.v1.Event.RoleMoved': $8.Event_RoleMoved$json,
  '.protocol.chat.v1.Event.ProfileUpdated': $8.Event_ProfileUpdated$json,
  '.protocol.chat.v1.Event.Typing': $8.Event_Typing$json,
  '.protocol.chat.v1.GetUserRequest': $9.GetUserRequest$json,
  '.protocol.chat.v1.GetUserResponse': $9.GetUserResponse$json,
  '.protocol.chat.v1.GetUserMetadataRequest': $9.GetUserMetadataRequest$json,
  '.protocol.chat.v1.GetUserMetadataResponse': $9.GetUserMetadataResponse$json,
  '.protocol.chat.v1.ProfileUpdateRequest': $9.ProfileUpdateRequest$json,
  '.protocol.chat.v1.TypingRequest': $3.TypingRequest$json,
  '.protocol.chat.v1.PreviewGuildRequest': $2.PreviewGuildRequest$json,
  '.protocol.chat.v1.PreviewGuildResponse': $2.PreviewGuildResponse$json,
};

