///
//  Generated code. Do not modify.
//  source: chat/v1/chat.proto
//
// @dart = 2.12
// ignore_for_file: annotate_overrides,camel_case_types,unnecessary_const,non_constant_identifier_names,library_prefixes,unused_import,unused_shown_name,return_of_invalid_type,unnecessary_this,prefer_final_fields,deprecated_member_use_from_same_package

import 'dart:core' as $core;
import 'dart:convert' as $convert;
import 'dart:typed_data' as $typed_data;
import 'guilds.pbjson.dart' as $7;
import '../../harmonytypes/v1/types.pbjson.dart' as $0;
import 'private_channel.pbjson.dart' as $8;
import 'channels.pbjson.dart' as $6;
import 'messages.pbjson.dart' as $4;
import '../../emote/v1/types.pbjson.dart' as $1;
import 'permissions.pbjson.dart' as $5;
import 'stream.pbjson.dart' as $9;
import '../../emote/v1/stream.pbjson.dart' as $2;
import '../../profile/v1/stream.pbjson.dart' as $3;
import '../../profile/v1/types.pbjson.dart' as $10;

const $core.Map<$core.String, $core.dynamic> ChatServiceBase$json = const {
  '1': 'ChatService',
  '2': const [
    const {'1': 'CreateGuild', '2': '.protocol.chat.v1.CreateGuildRequest', '3': '.protocol.chat.v1.CreateGuildResponse', '4': const {}},
    const {'1': 'CreatePrivateChannel', '2': '.protocol.chat.v1.CreatePrivateChannelRequest', '3': '.protocol.chat.v1.CreatePrivateChannelResponse', '4': const {}},
    const {'1': 'UpdatePrivateChannelMembers', '2': '.protocol.chat.v1.UpdatePrivateChannelMembersRequest', '3': '.protocol.chat.v1.UpdatePrivateChannelMembersResponse', '4': const {}},
    const {'1': 'UpdatePrivateChannelName', '2': '.protocol.chat.v1.UpdatePrivateChannelNameRequest', '3': '.protocol.chat.v1.UpdatePrivateChannelNameResponse', '4': const {}},
    const {'1': 'DeletePrivateChannel', '2': '.protocol.chat.v1.DeletePrivateChannelRequest', '3': '.protocol.chat.v1.DeletePrivateChannelResponse', '4': const {}},
    const {'1': 'JoinPrivateChannel', '2': '.protocol.chat.v1.JoinPrivateChannelRequest', '3': '.protocol.chat.v1.JoinPrivateChannelResponse', '4': const {}},
    const {'1': 'LeavePrivateChannel', '2': '.protocol.chat.v1.LeavePrivateChannelRequest', '3': '.protocol.chat.v1.LeavePrivateChannelResponse', '4': const {}},
    const {'1': 'CreateInvite', '2': '.protocol.chat.v1.CreateInviteRequest', '3': '.protocol.chat.v1.CreateInviteResponse', '4': const {}},
    const {'1': 'CreateChannel', '2': '.protocol.chat.v1.CreateChannelRequest', '3': '.protocol.chat.v1.CreateChannelResponse', '4': const {}},
    const {'1': 'GetGuildList', '2': '.protocol.chat.v1.GetGuildListRequest', '3': '.protocol.chat.v1.GetGuildListResponse', '4': const {}},
    const {'1': 'GetPrivateChannelList', '2': '.protocol.chat.v1.GetPrivateChannelListRequest', '3': '.protocol.chat.v1.GetPrivateChannelListResponse', '4': const {}},
    const {'1': 'GetPrivateChannel', '2': '.protocol.chat.v1.GetPrivateChannelRequest', '3': '.protocol.chat.v1.GetPrivateChannelResponse', '4': const {}},
    const {'1': 'InviteUserToGuild', '2': '.protocol.chat.v1.InviteUserToGuildRequest', '3': '.protocol.chat.v1.InviteUserToGuildResponse', '4': const {}},
    const {'1': 'GetPendingInvites', '2': '.protocol.chat.v1.GetPendingInvitesRequest', '3': '.protocol.chat.v1.GetPendingInvitesResponse', '4': const {}},
    const {'1': 'RejectPendingInvite', '2': '.protocol.chat.v1.RejectPendingInviteRequest', '3': '.protocol.chat.v1.RejectPendingInviteResponse', '4': const {}},
    const {'1': 'IgnorePendingInvite', '2': '.protocol.chat.v1.IgnorePendingInviteRequest', '3': '.protocol.chat.v1.IgnorePendingInviteResponse', '4': const {}},
    const {'1': 'GetGuild', '2': '.protocol.chat.v1.GetGuildRequest', '3': '.protocol.chat.v1.GetGuildResponse', '4': const {}},
    const {'1': 'GetGuildInvites', '2': '.protocol.chat.v1.GetGuildInvitesRequest', '3': '.protocol.chat.v1.GetGuildInvitesResponse', '4': const {}},
    const {'1': 'GetGuildMembers', '2': '.protocol.chat.v1.GetGuildMembersRequest', '3': '.protocol.chat.v1.GetGuildMembersResponse', '4': const {}},
    const {'1': 'GetGuildChannels', '2': '.protocol.chat.v1.GetGuildChannelsRequest', '3': '.protocol.chat.v1.GetGuildChannelsResponse', '4': const {}},
    const {'1': 'GetChannelMessages', '2': '.protocol.chat.v1.GetChannelMessagesRequest', '3': '.protocol.chat.v1.GetChannelMessagesResponse', '4': const {}},
    const {'1': 'GetMessage', '2': '.protocol.chat.v1.GetMessageRequest', '3': '.protocol.chat.v1.GetMessageResponse', '4': const {}},
    const {'1': 'UpdateGuildInformation', '2': '.protocol.chat.v1.UpdateGuildInformationRequest', '3': '.protocol.chat.v1.UpdateGuildInformationResponse', '4': const {}},
    const {'1': 'UpdateChannelInformation', '2': '.protocol.chat.v1.UpdateChannelInformationRequest', '3': '.protocol.chat.v1.UpdateChannelInformationResponse', '4': const {}},
    const {'1': 'UpdateChannelOrder', '2': '.protocol.chat.v1.UpdateChannelOrderRequest', '3': '.protocol.chat.v1.UpdateChannelOrderResponse', '4': const {}},
    const {'1': 'UpdateAllChannelOrder', '2': '.protocol.chat.v1.UpdateAllChannelOrderRequest', '3': '.protocol.chat.v1.UpdateAllChannelOrderResponse', '4': const {}},
    const {'1': 'UpdateMessageContent', '2': '.protocol.chat.v1.UpdateMessageContentRequest', '3': '.protocol.chat.v1.UpdateMessageContentResponse', '4': const {}},
    const {'1': 'DeleteGuild', '2': '.protocol.chat.v1.DeleteGuildRequest', '3': '.protocol.chat.v1.DeleteGuildResponse', '4': const {}},
    const {'1': 'DeleteInvite', '2': '.protocol.chat.v1.DeleteInviteRequest', '3': '.protocol.chat.v1.DeleteInviteResponse', '4': const {}},
    const {'1': 'DeleteChannel', '2': '.protocol.chat.v1.DeleteChannelRequest', '3': '.protocol.chat.v1.DeleteChannelResponse', '4': const {}},
    const {'1': 'DeleteMessage', '2': '.protocol.chat.v1.DeleteMessageRequest', '3': '.protocol.chat.v1.DeleteMessageResponse', '4': const {}},
    const {'1': 'JoinGuild', '2': '.protocol.chat.v1.JoinGuildRequest', '3': '.protocol.chat.v1.JoinGuildResponse', '4': const {}},
    const {'1': 'LeaveGuild', '2': '.protocol.chat.v1.LeaveGuildRequest', '3': '.protocol.chat.v1.LeaveGuildResponse', '4': const {}},
    const {'1': 'TriggerAction', '2': '.protocol.chat.v1.TriggerActionRequest', '3': '.protocol.chat.v1.TriggerActionResponse', '4': const {}},
    const {'1': 'SendMessage', '2': '.protocol.chat.v1.SendMessageRequest', '3': '.protocol.chat.v1.SendMessageResponse', '4': const {}},
    const {'1': 'HasPermission', '2': '.protocol.chat.v1.HasPermissionRequest', '3': '.protocol.chat.v1.HasPermissionResponse', '4': const {}},
    const {'1': 'SetPermissions', '2': '.protocol.chat.v1.SetPermissionsRequest', '3': '.protocol.chat.v1.SetPermissionsResponse', '4': const {}},
    const {'1': 'GetPermissions', '2': '.protocol.chat.v1.GetPermissionsRequest', '3': '.protocol.chat.v1.GetPermissionsResponse', '4': const {}},
    const {'1': 'MoveRole', '2': '.protocol.chat.v1.MoveRoleRequest', '3': '.protocol.chat.v1.MoveRoleResponse', '4': const {}},
    const {'1': 'GetGuildRoles', '2': '.protocol.chat.v1.GetGuildRolesRequest', '3': '.protocol.chat.v1.GetGuildRolesResponse', '4': const {}},
    const {'1': 'AddGuildRole', '2': '.protocol.chat.v1.AddGuildRoleRequest', '3': '.protocol.chat.v1.AddGuildRoleResponse', '4': const {}},
    const {'1': 'ModifyGuildRole', '2': '.protocol.chat.v1.ModifyGuildRoleRequest', '3': '.protocol.chat.v1.ModifyGuildRoleResponse', '4': const {}},
    const {'1': 'DeleteGuildRole', '2': '.protocol.chat.v1.DeleteGuildRoleRequest', '3': '.protocol.chat.v1.DeleteGuildRoleResponse', '4': const {}},
    const {'1': 'ManageUserRoles', '2': '.protocol.chat.v1.ManageUserRolesRequest', '3': '.protocol.chat.v1.ManageUserRolesResponse', '4': const {}},
    const {'1': 'GetUserRoles', '2': '.protocol.chat.v1.GetUserRolesRequest', '3': '.protocol.chat.v1.GetUserRolesResponse', '4': const {}},
    const {'1': 'Typing', '2': '.protocol.chat.v1.TypingRequest', '3': '.protocol.chat.v1.TypingResponse', '4': const {}},
    const {'1': 'PreviewGuild', '2': '.protocol.chat.v1.PreviewGuildRequest', '3': '.protocol.chat.v1.PreviewGuildResponse', '4': const {}},
    const {'1': 'GetBannedUsers', '2': '.protocol.chat.v1.GetBannedUsersRequest', '3': '.protocol.chat.v1.GetBannedUsersResponse', '4': const {}},
    const {'1': 'BanUser', '2': '.protocol.chat.v1.BanUserRequest', '3': '.protocol.chat.v1.BanUserResponse', '4': const {}},
    const {'1': 'KickUser', '2': '.protocol.chat.v1.KickUserRequest', '3': '.protocol.chat.v1.KickUserResponse', '4': const {}},
    const {'1': 'UnbanUser', '2': '.protocol.chat.v1.UnbanUserRequest', '3': '.protocol.chat.v1.UnbanUserResponse', '4': const {}},
    const {'1': 'GetPinnedMessages', '2': '.protocol.chat.v1.GetPinnedMessagesRequest', '3': '.protocol.chat.v1.GetPinnedMessagesResponse', '4': const {}},
    const {'1': 'PinMessage', '2': '.protocol.chat.v1.PinMessageRequest', '3': '.protocol.chat.v1.PinMessageResponse', '4': const {}},
    const {'1': 'UnpinMessage', '2': '.protocol.chat.v1.UnpinMessageRequest', '3': '.protocol.chat.v1.UnpinMessageResponse', '4': const {}},
    const {'1': 'StreamEvents', '2': '.protocol.chat.v1.StreamEventsRequest', '3': '.protocol.chat.v1.StreamEventsResponse', '4': const {}, '5': true, '6': true},
    const {'1': 'AddReaction', '2': '.protocol.chat.v1.AddReactionRequest', '3': '.protocol.chat.v1.AddReactionResponse', '4': const {}},
    const {'1': 'RemoveReaction', '2': '.protocol.chat.v1.RemoveReactionRequest', '3': '.protocol.chat.v1.RemoveReactionResponse', '4': const {}},
    const {'1': 'GrantOwnership', '2': '.protocol.chat.v1.GrantOwnershipRequest', '3': '.protocol.chat.v1.GrantOwnershipResponse', '4': const {}},
    const {'1': 'GiveUpOwnership', '2': '.protocol.chat.v1.GiveUpOwnershipRequest', '3': '.protocol.chat.v1.GiveUpOwnershipResponse', '4': const {}},
  ],
};

@$core.Deprecated('Use chatServiceDescriptor instead')
const $core.Map<$core.String, $core.Map<$core.String, $core.dynamic>> ChatServiceBase$messageJson = const {
  '.protocol.chat.v1.CreateGuildRequest': $7.CreateGuildRequest$json,
  '.protocol.harmonytypes.v1.Metadata': $0.Metadata$json,
  '.protocol.harmonytypes.v1.Metadata.ExtensionEntry': $0.Metadata_ExtensionEntry$json,
  '.protocol.harmonytypes.v1.Anything': $0.Anything$json,
  '.protocol.chat.v1.CreateGuildResponse': $7.CreateGuildResponse$json,
  '.protocol.chat.v1.CreatePrivateChannelRequest': $8.CreatePrivateChannelRequest$json,
  '.protocol.chat.v1.CreatePrivateChannelResponse': $8.CreatePrivateChannelResponse$json,
  '.protocol.chat.v1.UpdatePrivateChannelMembersRequest': $8.UpdatePrivateChannelMembersRequest$json,
  '.protocol.chat.v1.UpdatePrivateChannelMembersResponse': $8.UpdatePrivateChannelMembersResponse$json,
  '.protocol.chat.v1.UpdatePrivateChannelNameRequest': $8.UpdatePrivateChannelNameRequest$json,
  '.protocol.chat.v1.UpdatePrivateChannelNameResponse': $8.UpdatePrivateChannelNameResponse$json,
  '.protocol.chat.v1.DeletePrivateChannelRequest': $8.DeletePrivateChannelRequest$json,
  '.protocol.chat.v1.DeletePrivateChannelResponse': $8.DeletePrivateChannelResponse$json,
  '.protocol.chat.v1.JoinPrivateChannelRequest': $8.JoinPrivateChannelRequest$json,
  '.protocol.chat.v1.JoinPrivateChannelResponse': $8.JoinPrivateChannelResponse$json,
  '.protocol.chat.v1.LeavePrivateChannelRequest': $8.LeavePrivateChannelRequest$json,
  '.protocol.chat.v1.LeavePrivateChannelResponse': $8.LeavePrivateChannelResponse$json,
  '.protocol.chat.v1.CreateInviteRequest': $7.CreateInviteRequest$json,
  '.protocol.chat.v1.CreateInviteResponse': $7.CreateInviteResponse$json,
  '.protocol.chat.v1.CreateChannelRequest': $6.CreateChannelRequest$json,
  '.protocol.harmonytypes.v1.ItemPosition': $0.ItemPosition$json,
  '.protocol.chat.v1.CreateChannelResponse': $6.CreateChannelResponse$json,
  '.protocol.chat.v1.GetGuildListRequest': $7.GetGuildListRequest$json,
  '.protocol.chat.v1.GetGuildListResponse': $7.GetGuildListResponse$json,
  '.protocol.chat.v1.GuildListEntry': $7.GuildListEntry$json,
  '.protocol.chat.v1.GetPrivateChannelListRequest': $8.GetPrivateChannelListRequest$json,
  '.protocol.chat.v1.GetPrivateChannelListResponse': $8.GetPrivateChannelListResponse$json,
  '.protocol.chat.v1.PrivateChannelListEntry': $8.PrivateChannelListEntry$json,
  '.protocol.chat.v1.GetPrivateChannelRequest': $8.GetPrivateChannelRequest$json,
  '.protocol.chat.v1.GetPrivateChannelResponse': $8.GetPrivateChannelResponse$json,
  '.protocol.chat.v1.GetPrivateChannelResponse.ChannelsEntry': $8.GetPrivateChannelResponse_ChannelsEntry$json,
  '.protocol.chat.v1.PrivateChannel': $8.PrivateChannel$json,
  '.protocol.chat.v1.InviteUserToGuildRequest': $7.InviteUserToGuildRequest$json,
  '.protocol.chat.v1.InviteUserToGuildResponse': $7.InviteUserToGuildResponse$json,
  '.protocol.chat.v1.GetPendingInvitesRequest': $7.GetPendingInvitesRequest$json,
  '.protocol.chat.v1.GetPendingInvitesResponse': $7.GetPendingInvitesResponse$json,
  '.protocol.chat.v1.PendingInvite': $7.PendingInvite$json,
  '.protocol.chat.v1.RejectPendingInviteRequest': $7.RejectPendingInviteRequest$json,
  '.protocol.chat.v1.RejectPendingInviteResponse': $7.RejectPendingInviteResponse$json,
  '.protocol.chat.v1.IgnorePendingInviteRequest': $7.IgnorePendingInviteRequest$json,
  '.protocol.chat.v1.IgnorePendingInviteResponse': $7.IgnorePendingInviteResponse$json,
  '.protocol.chat.v1.GetGuildRequest': $7.GetGuildRequest$json,
  '.protocol.chat.v1.GetGuildResponse': $7.GetGuildResponse$json,
  '.protocol.chat.v1.GetGuildResponse.GuildEntry': $7.GetGuildResponse_GuildEntry$json,
  '.protocol.chat.v1.Guild': $7.Guild$json,
  '.protocol.chat.v1.GetGuildInvitesRequest': $7.GetGuildInvitesRequest$json,
  '.protocol.chat.v1.GetGuildInvitesResponse': $7.GetGuildInvitesResponse$json,
  '.protocol.chat.v1.InviteWithId': $7.InviteWithId$json,
  '.protocol.chat.v1.Invite': $7.Invite$json,
  '.protocol.chat.v1.GetGuildMembersRequest': $7.GetGuildMembersRequest$json,
  '.protocol.chat.v1.GetGuildMembersResponse': $7.GetGuildMembersResponse$json,
  '.protocol.chat.v1.GetGuildChannelsRequest': $6.GetGuildChannelsRequest$json,
  '.protocol.chat.v1.GetGuildChannelsResponse': $6.GetGuildChannelsResponse$json,
  '.protocol.chat.v1.ChannelWithId': $6.ChannelWithId$json,
  '.protocol.chat.v1.Channel': $6.Channel$json,
  '.protocol.chat.v1.GetChannelMessagesRequest': $4.GetChannelMessagesRequest$json,
  '.protocol.chat.v1.GetChannelMessagesResponse': $4.GetChannelMessagesResponse$json,
  '.protocol.chat.v1.MessageWithId': $4.MessageWithId$json,
  '.protocol.chat.v1.Message': $4.Message$json,
  '.protocol.chat.v1.Overrides': $4.Overrides$json,
  '.protocol.harmonytypes.v1.Empty': $0.Empty$json,
  '.protocol.chat.v1.Content': $4.Content$json,
  '.protocol.chat.v1.Format': $4.Format$json,
  '.protocol.chat.v1.Format.Bold': $4.Format_Bold$json,
  '.protocol.chat.v1.Format.Italic': $4.Format_Italic$json,
  '.protocol.chat.v1.Format.Underline': $4.Format_Underline$json,
  '.protocol.chat.v1.Format.Monospace': $4.Format_Monospace$json,
  '.protocol.chat.v1.Format.Superscript': $4.Format_Superscript$json,
  '.protocol.chat.v1.Format.Subscript': $4.Format_Subscript$json,
  '.protocol.chat.v1.Format.CodeBlock': $4.Format_CodeBlock$json,
  '.protocol.chat.v1.Format.UserMention': $4.Format_UserMention$json,
  '.protocol.chat.v1.Format.RoleMention': $4.Format_RoleMention$json,
  '.protocol.chat.v1.Format.ChannelMention': $4.Format_ChannelMention$json,
  '.protocol.chat.v1.Format.GuildMention': $4.Format_GuildMention$json,
  '.protocol.chat.v1.Format.Emoji': $4.Format_Emoji$json,
  '.protocol.emote.v1.Emote': $1.Emote$json,
  '.protocol.chat.v1.Format.Color': $4.Format_Color$json,
  '.protocol.chat.v1.Embed': $4.Embed$json,
  '.protocol.chat.v1.Embed.Heading': $4.Embed_Heading$json,
  '.protocol.chat.v1.FormattedText': $4.FormattedText$json,
  '.protocol.chat.v1.Embed.Field': $4.Embed_Field$json,
  '.protocol.chat.v1.Embed.Image': $4.Embed_Image$json,
  '.protocol.chat.v1.Action': $4.Action$json,
  '.protocol.chat.v1.Action.Button': $4.Action_Button$json,
  '.protocol.chat.v1.Action.Dropdown': $4.Action_Dropdown$json,
  '.protocol.chat.v1.Action.Dropdown.Entry': $4.Action_Dropdown_Entry$json,
  '.protocol.chat.v1.Action.Input': $4.Action_Input$json,
  '.protocol.chat.v1.Attachment': $4.Attachment$json,
  '.protocol.chat.v1.Attachment.ImageInfo': $4.Attachment_ImageInfo$json,
  '.protocol.chat.v1.Minithumbnail': $4.Minithumbnail$json,
  '.protocol.chat.v1.Content.InviteRejected': $4.Content_InviteRejected$json,
  '.protocol.chat.v1.Content.InviteAccepted': $4.Content_InviteAccepted$json,
  '.protocol.chat.v1.Content.RoomUpgradedToGuild': $4.Content_RoomUpgradedToGuild$json,
  '.protocol.chat.v1.Reaction': $4.Reaction$json,
  '.protocol.chat.v1.GetMessageRequest': $4.GetMessageRequest$json,
  '.protocol.chat.v1.GetMessageResponse': $4.GetMessageResponse$json,
  '.protocol.chat.v1.UpdateGuildInformationRequest': $7.UpdateGuildInformationRequest$json,
  '.protocol.chat.v1.UpdateGuildInformationResponse': $7.UpdateGuildInformationResponse$json,
  '.protocol.chat.v1.UpdateChannelInformationRequest': $6.UpdateChannelInformationRequest$json,
  '.protocol.chat.v1.UpdateChannelInformationResponse': $6.UpdateChannelInformationResponse$json,
  '.protocol.chat.v1.UpdateChannelOrderRequest': $6.UpdateChannelOrderRequest$json,
  '.protocol.chat.v1.UpdateChannelOrderResponse': $6.UpdateChannelOrderResponse$json,
  '.protocol.chat.v1.UpdateAllChannelOrderRequest': $6.UpdateAllChannelOrderRequest$json,
  '.protocol.chat.v1.UpdateAllChannelOrderResponse': $6.UpdateAllChannelOrderResponse$json,
  '.protocol.chat.v1.UpdateMessageContentRequest': $4.UpdateMessageContentRequest$json,
  '.protocol.chat.v1.SendMessageRequest.Content': $4.SendMessageRequest_Content$json,
  '.protocol.chat.v1.SendMessageRequest.Attachment': $4.SendMessageRequest_Attachment$json,
  '.protocol.chat.v1.SendMessageRequest.Attachment.ImageInfo': $4.SendMessageRequest_Attachment_ImageInfo$json,
  '.protocol.chat.v1.UpdateMessageContentResponse': $4.UpdateMessageContentResponse$json,
  '.protocol.chat.v1.DeleteGuildRequest': $7.DeleteGuildRequest$json,
  '.protocol.chat.v1.DeleteGuildResponse': $7.DeleteGuildResponse$json,
  '.protocol.chat.v1.DeleteInviteRequest': $7.DeleteInviteRequest$json,
  '.protocol.chat.v1.DeleteInviteResponse': $7.DeleteInviteResponse$json,
  '.protocol.chat.v1.DeleteChannelRequest': $6.DeleteChannelRequest$json,
  '.protocol.chat.v1.DeleteChannelResponse': $6.DeleteChannelResponse$json,
  '.protocol.chat.v1.DeleteMessageRequest': $4.DeleteMessageRequest$json,
  '.protocol.chat.v1.DeleteMessageResponse': $4.DeleteMessageResponse$json,
  '.protocol.chat.v1.JoinGuildRequest': $7.JoinGuildRequest$json,
  '.protocol.chat.v1.JoinGuildResponse': $7.JoinGuildResponse$json,
  '.protocol.chat.v1.LeaveGuildRequest': $7.LeaveGuildRequest$json,
  '.protocol.chat.v1.LeaveGuildResponse': $7.LeaveGuildResponse$json,
  '.protocol.chat.v1.TriggerActionRequest': $4.TriggerActionRequest$json,
  '.protocol.chat.v1.TriggerActionResponse': $4.TriggerActionResponse$json,
  '.protocol.chat.v1.SendMessageRequest': $4.SendMessageRequest$json,
  '.protocol.chat.v1.SendMessageResponse': $4.SendMessageResponse$json,
  '.protocol.chat.v1.HasPermissionRequest': $5.HasPermissionRequest$json,
  '.protocol.chat.v1.HasPermissionResponse': $5.HasPermissionResponse$json,
  '.protocol.chat.v1.Permission': $5.Permission$json,
  '.protocol.chat.v1.SetPermissionsRequest': $5.SetPermissionsRequest$json,
  '.protocol.chat.v1.SetPermissionsResponse': $5.SetPermissionsResponse$json,
  '.protocol.chat.v1.GetPermissionsRequest': $5.GetPermissionsRequest$json,
  '.protocol.chat.v1.GetPermissionsResponse': $5.GetPermissionsResponse$json,
  '.protocol.chat.v1.GetPermissionsResponse.Permissions': $5.GetPermissionsResponse_Permissions$json,
  '.protocol.chat.v1.GetPermissionsResponse.ChannelPermsEntry': $5.GetPermissionsResponse_ChannelPermsEntry$json,
  '.protocol.chat.v1.MoveRoleRequest': $5.MoveRoleRequest$json,
  '.protocol.chat.v1.MoveRoleResponse': $5.MoveRoleResponse$json,
  '.protocol.chat.v1.GetGuildRolesRequest': $5.GetGuildRolesRequest$json,
  '.protocol.chat.v1.GetGuildRolesResponse': $5.GetGuildRolesResponse$json,
  '.protocol.chat.v1.RoleWithId': $5.RoleWithId$json,
  '.protocol.chat.v1.Role': $5.Role$json,
  '.protocol.chat.v1.AddGuildRoleRequest': $5.AddGuildRoleRequest$json,
  '.protocol.chat.v1.AddGuildRoleResponse': $5.AddGuildRoleResponse$json,
  '.protocol.chat.v1.ModifyGuildRoleRequest': $5.ModifyGuildRoleRequest$json,
  '.protocol.chat.v1.ModifyGuildRoleResponse': $5.ModifyGuildRoleResponse$json,
  '.protocol.chat.v1.DeleteGuildRoleRequest': $5.DeleteGuildRoleRequest$json,
  '.protocol.chat.v1.DeleteGuildRoleResponse': $5.DeleteGuildRoleResponse$json,
  '.protocol.chat.v1.ManageUserRolesRequest': $5.ManageUserRolesRequest$json,
  '.protocol.chat.v1.ManageUserRolesResponse': $5.ManageUserRolesResponse$json,
  '.protocol.chat.v1.GetUserRolesRequest': $5.GetUserRolesRequest$json,
  '.protocol.chat.v1.GetUserRolesResponse': $5.GetUserRolesResponse$json,
  '.protocol.chat.v1.GetUserRolesResponse.UserRolesEntry': $5.GetUserRolesResponse_UserRolesEntry$json,
  '.protocol.chat.v1.GetUserRolesResponse.UserRoles': $5.GetUserRolesResponse_UserRoles$json,
  '.protocol.chat.v1.TypingRequest': $4.TypingRequest$json,
  '.protocol.chat.v1.TypingResponse': $4.TypingResponse$json,
  '.protocol.chat.v1.PreviewGuildRequest': $7.PreviewGuildRequest$json,
  '.protocol.chat.v1.PreviewGuildResponse': $7.PreviewGuildResponse$json,
  '.protocol.chat.v1.GetBannedUsersRequest': $7.GetBannedUsersRequest$json,
  '.protocol.chat.v1.GetBannedUsersResponse': $7.GetBannedUsersResponse$json,
  '.protocol.chat.v1.BanUserRequest': $7.BanUserRequest$json,
  '.protocol.chat.v1.BanUserResponse': $7.BanUserResponse$json,
  '.protocol.chat.v1.KickUserRequest': $7.KickUserRequest$json,
  '.protocol.chat.v1.KickUserResponse': $7.KickUserResponse$json,
  '.protocol.chat.v1.UnbanUserRequest': $7.UnbanUserRequest$json,
  '.protocol.chat.v1.UnbanUserResponse': $7.UnbanUserResponse$json,
  '.protocol.chat.v1.GetPinnedMessagesRequest': $4.GetPinnedMessagesRequest$json,
  '.protocol.chat.v1.GetPinnedMessagesResponse': $4.GetPinnedMessagesResponse$json,
  '.protocol.chat.v1.PinMessageRequest': $4.PinMessageRequest$json,
  '.protocol.chat.v1.PinMessageResponse': $4.PinMessageResponse$json,
  '.protocol.chat.v1.UnpinMessageRequest': $4.UnpinMessageRequest$json,
  '.protocol.chat.v1.UnpinMessageResponse': $4.UnpinMessageResponse$json,
  '.protocol.chat.v1.StreamEventsRequest': $9.StreamEventsRequest$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToGuild': $9.StreamEventsRequest_SubscribeToGuild$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToPrivateChannel': $9.StreamEventsRequest_SubscribeToPrivateChannel$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToActions': $9.StreamEventsRequest_SubscribeToActions$json,
  '.protocol.chat.v1.StreamEventsRequest.SubscribeToHomeserverEvents': $9.StreamEventsRequest_SubscribeToHomeserverEvents$json,
  '.protocol.chat.v1.StreamEventsRequest.UnsubscribeFromAll': $9.StreamEventsRequest_UnsubscribeFromAll$json,
  '.protocol.chat.v1.StreamEventsResponse': $9.StreamEventsResponse$json,
  '.protocol.chat.v1.StreamEvent': $9.StreamEvent$json,
  '.protocol.chat.v1.StreamEvent.GuildAddedToList': $9.StreamEvent_GuildAddedToList$json,
  '.protocol.chat.v1.StreamEvent.GuildRemovedFromList': $9.StreamEvent_GuildRemovedFromList$json,
  '.protocol.chat.v1.StreamEvent.ActionPerformed': $9.StreamEvent_ActionPerformed$json,
  '.protocol.chat.v1.StreamEvent.MessageSent': $9.StreamEvent_MessageSent$json,
  '.protocol.chat.v1.StreamEvent.MessageUpdated': $9.StreamEvent_MessageUpdated$json,
  '.protocol.chat.v1.StreamEvent.MessageDeleted': $9.StreamEvent_MessageDeleted$json,
  '.protocol.chat.v1.StreamEvent.ChannelCreated': $9.StreamEvent_ChannelCreated$json,
  '.protocol.chat.v1.StreamEvent.ChannelUpdated': $9.StreamEvent_ChannelUpdated$json,
  '.protocol.chat.v1.StreamEvent.ChannelDeleted': $9.StreamEvent_ChannelDeleted$json,
  '.protocol.chat.v1.StreamEvent.GuildUpdated': $9.StreamEvent_GuildUpdated$json,
  '.protocol.chat.v1.StreamEvent.GuildDeleted': $9.StreamEvent_GuildDeleted$json,
  '.protocol.chat.v1.StreamEvent.MemberJoined': $9.StreamEvent_MemberJoined$json,
  '.protocol.chat.v1.StreamEvent.MemberLeft': $9.StreamEvent_MemberLeft$json,
  '.protocol.chat.v1.StreamEvent.Typing': $9.StreamEvent_Typing$json,
  '.protocol.chat.v1.StreamEvent.RoleCreated': $9.StreamEvent_RoleCreated$json,
  '.protocol.chat.v1.StreamEvent.RoleDeleted': $9.StreamEvent_RoleDeleted$json,
  '.protocol.chat.v1.StreamEvent.RoleMoved': $9.StreamEvent_RoleMoved$json,
  '.protocol.chat.v1.StreamEvent.RoleUpdated': $9.StreamEvent_RoleUpdated$json,
  '.protocol.chat.v1.StreamEvent.RolePermissionsUpdated': $9.StreamEvent_RolePermissionsUpdated$json,
  '.protocol.chat.v1.StreamEvent.UserRolesUpdated': $9.StreamEvent_UserRolesUpdated$json,
  '.protocol.chat.v1.StreamEvent.PermissionUpdated': $9.StreamEvent_PermissionUpdated$json,
  '.protocol.chat.v1.StreamEvent.ChannelsReordered': $9.StreamEvent_ChannelsReordered$json,
  '.protocol.chat.v1.StreamEvent.ChannelPositionUpdated': $9.StreamEvent_ChannelPositionUpdated$json,
  '.protocol.chat.v1.StreamEvent.MessagePinned': $9.StreamEvent_MessagePinned$json,
  '.protocol.chat.v1.StreamEvent.MessageUnpinned': $9.StreamEvent_MessageUnpinned$json,
  '.protocol.chat.v1.StreamEvent.OwnerAdded': $9.StreamEvent_OwnerAdded$json,
  '.protocol.chat.v1.StreamEvent.OwnerRemoved': $9.StreamEvent_OwnerRemoved$json,
  '.protocol.chat.v1.StreamEvent.InviteReceived': $9.StreamEvent_InviteReceived$json,
  '.protocol.chat.v1.StreamEvent.InviteRejected': $9.StreamEvent_InviteRejected$json,
  '.protocol.chat.v1.StreamEvent.InviteCreated': $9.StreamEvent_InviteCreated$json,
  '.protocol.chat.v1.StreamEvent.InviteDeleted': $9.StreamEvent_InviteDeleted$json,
  '.protocol.chat.v1.StreamEvent.InviteUsed': $9.StreamEvent_InviteUsed$json,
  '.protocol.chat.v1.StreamEvent.NewReactionAdded': $9.StreamEvent_NewReactionAdded$json,
  '.protocol.chat.v1.StreamEvent.ReactionAdded': $9.StreamEvent_ReactionAdded$json,
  '.protocol.chat.v1.StreamEvent.ReactionRemoved': $9.StreamEvent_ReactionRemoved$json,
  '.protocol.chat.v1.StreamEvent.PrivateChannelDeleted': $9.StreamEvent_PrivateChannelDeleted$json,
  '.protocol.chat.v1.StreamEvent.PrivateChannelAddedToList': $9.StreamEvent_PrivateChannelAddedToList$json,
  '.protocol.chat.v1.StreamEvent.PrivateChannelRemovedFromList': $9.StreamEvent_PrivateChannelRemovedFromList$json,
  '.protocol.chat.v1.StreamEvent.UserJoinedPrivateChannel': $9.StreamEvent_UserJoinedPrivateChannel$json,
  '.protocol.chat.v1.StreamEvent.UserLeftPrivateChannel': $9.StreamEvent_UserLeftPrivateChannel$json,
  '.protocol.emote.v1.StreamEvent': $2.StreamEvent$json,
  '.protocol.emote.v1.EmotePackAdded': $2.EmotePackAdded$json,
  '.protocol.emote.v1.EmotePack': $1.EmotePack$json,
  '.protocol.emote.v1.EmotePackUpdated': $2.EmotePackUpdated$json,
  '.protocol.emote.v1.EmotePackDeleted': $2.EmotePackDeleted$json,
  '.protocol.emote.v1.EmotePackEmotesUpdated': $2.EmotePackEmotesUpdated$json,
  '.protocol.profile.v1.StreamEvent': $3.StreamEvent$json,
  '.protocol.profile.v1.ProfileUpdated': $3.ProfileUpdated$json,
  '.protocol.profile.v1.StatusUpdated': $3.StatusUpdated$json,
  '.protocol.profile.v1.UserStatus': $10.UserStatus$json,
  '.protocol.profile.v1.UserStatus.Activity': $10.UserStatus_Activity$json,
  '.protocol.profile.v1.UserStatus.Action': $10.UserStatus_Action$json,
  '.protocol.chat.v1.AddReactionRequest': $4.AddReactionRequest$json,
  '.protocol.chat.v1.AddReactionResponse': $4.AddReactionResponse$json,
  '.protocol.chat.v1.RemoveReactionRequest': $4.RemoveReactionRequest$json,
  '.protocol.chat.v1.RemoveReactionResponse': $4.RemoveReactionResponse$json,
  '.protocol.chat.v1.GrantOwnershipRequest': $7.GrantOwnershipRequest$json,
  '.protocol.chat.v1.GrantOwnershipResponse': $7.GrantOwnershipResponse$json,
  '.protocol.chat.v1.GiveUpOwnershipRequest': $7.GiveUpOwnershipRequest$json,
  '.protocol.chat.v1.GiveUpOwnershipResponse': $7.GiveUpOwnershipResponse$json,
};

/// Descriptor for `ChatService`. Decode as a `google.protobuf.ServiceDescriptorProto`.
final $typed_data.Uint8List chatServiceDescriptor = $convert.base64Decode('CgtDaGF0U2VydmljZRJhCgtDcmVhdGVHdWlsZBIkLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlR3VpbGRSZXF1ZXN0GiUucHJvdG9jb2wuY2hhdC52MS5DcmVhdGVHdWlsZFJlc3BvbnNlIgWaRAIIARJ8ChRDcmVhdGVQcml2YXRlQ2hhbm5lbBItLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlUHJpdmF0ZUNoYW5uZWxSZXF1ZXN0Gi4ucHJvdG9jb2wuY2hhdC52MS5DcmVhdGVQcml2YXRlQ2hhbm5lbFJlc3BvbnNlIgWaRAIIARKRAQobVXBkYXRlUHJpdmF0ZUNoYW5uZWxNZW1iZXJzEjQucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVQcml2YXRlQ2hhbm5lbE1lbWJlcnNSZXF1ZXN0GjUucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVQcml2YXRlQ2hhbm5lbE1lbWJlcnNSZXNwb25zZSIFmkQCCAESiAEKGFVwZGF0ZVByaXZhdGVDaGFubmVsTmFtZRIxLnByb3RvY29sLmNoYXQudjEuVXBkYXRlUHJpdmF0ZUNoYW5uZWxOYW1lUmVxdWVzdBoyLnByb3RvY29sLmNoYXQudjEuVXBkYXRlUHJpdmF0ZUNoYW5uZWxOYW1lUmVzcG9uc2UiBZpEAggBEnwKFERlbGV0ZVByaXZhdGVDaGFubmVsEi0ucHJvdG9jb2wuY2hhdC52MS5EZWxldGVQcml2YXRlQ2hhbm5lbFJlcXVlc3QaLi5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZVByaXZhdGVDaGFubmVsUmVzcG9uc2UiBZpEAggBEnYKEkpvaW5Qcml2YXRlQ2hhbm5lbBIrLnByb3RvY29sLmNoYXQudjEuSm9pblByaXZhdGVDaGFubmVsUmVxdWVzdBosLnByb3RvY29sLmNoYXQudjEuSm9pblByaXZhdGVDaGFubmVsUmVzcG9uc2UiBZpEAggBEnkKE0xlYXZlUHJpdmF0ZUNoYW5uZWwSLC5wcm90b2NvbC5jaGF0LnYxLkxlYXZlUHJpdmF0ZUNoYW5uZWxSZXF1ZXN0Gi0ucHJvdG9jb2wuY2hhdC52MS5MZWF2ZVByaXZhdGVDaGFubmVsUmVzcG9uc2UiBZpEAggBEn4KDENyZWF0ZUludml0ZRIlLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlSW52aXRlUmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuQ3JlYXRlSW52aXRlUmVzcG9uc2UiH5pEAggBmkQXGhVpbnZpdGVzLm1hbmFnZS5jcmVhdGUSggEKDUNyZWF0ZUNoYW5uZWwSJi5wcm90b2NvbC5jaGF0LnYxLkNyZWF0ZUNoYW5uZWxSZXF1ZXN0GicucHJvdG9jb2wuY2hhdC52MS5DcmVhdGVDaGFubmVsUmVzcG9uc2UiIJpEAggBmkQYGhZjaGFubmVscy5tYW5hZ2UuY3JlYXRlEmQKDEdldEd1aWxkTGlzdBIlLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRMaXN0UmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRMaXN0UmVzcG9uc2UiBZpEAggBEn8KFUdldFByaXZhdGVDaGFubmVsTGlzdBIuLnByb3RvY29sLmNoYXQudjEuR2V0UHJpdmF0ZUNoYW5uZWxMaXN0UmVxdWVzdBovLnByb3RvY29sLmNoYXQudjEuR2V0UHJpdmF0ZUNoYW5uZWxMaXN0UmVzcG9uc2UiBZpEAggBEnMKEUdldFByaXZhdGVDaGFubmVsEioucHJvdG9jb2wuY2hhdC52MS5HZXRQcml2YXRlQ2hhbm5lbFJlcXVlc3QaKy5wcm90b2NvbC5jaGF0LnYxLkdldFByaXZhdGVDaGFubmVsUmVzcG9uc2UiBZpEAggBEo0BChFJbnZpdGVVc2VyVG9HdWlsZBIqLnByb3RvY29sLmNoYXQudjEuSW52aXRlVXNlclRvR3VpbGRSZXF1ZXN0GisucHJvdG9jb2wuY2hhdC52MS5JbnZpdGVVc2VyVG9HdWlsZFJlc3BvbnNlIh+aRAIIAZpEFxoVaW52aXRlcy5tYW5hZ2UuY3JlYXRlEnMKEUdldFBlbmRpbmdJbnZpdGVzEioucHJvdG9jb2wuY2hhdC52MS5HZXRQZW5kaW5nSW52aXRlc1JlcXVlc3QaKy5wcm90b2NvbC5jaGF0LnYxLkdldFBlbmRpbmdJbnZpdGVzUmVzcG9uc2UiBZpEAggBEnkKE1JlamVjdFBlbmRpbmdJbnZpdGUSLC5wcm90b2NvbC5jaGF0LnYxLlJlamVjdFBlbmRpbmdJbnZpdGVSZXF1ZXN0Gi0ucHJvdG9jb2wuY2hhdC52MS5SZWplY3RQZW5kaW5nSW52aXRlUmVzcG9uc2UiBZpEAggBEnkKE0lnbm9yZVBlbmRpbmdJbnZpdGUSLC5wcm90b2NvbC5jaGF0LnYxLklnbm9yZVBlbmRpbmdJbnZpdGVSZXF1ZXN0Gi0ucHJvdG9jb2wuY2hhdC52MS5JZ25vcmVQZW5kaW5nSW52aXRlUmVzcG9uc2UiBZpEAggBElgKCEdldEd1aWxkEiEucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZFJlcXVlc3QaIi5wcm90b2NvbC5jaGF0LnYxLkdldEd1aWxkUmVzcG9uc2UiBZpEAggBEn4KD0dldEd1aWxkSW52aXRlcxIoLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRJbnZpdGVzUmVxdWVzdBopLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRJbnZpdGVzUmVzcG9uc2UiFppEAggBmkQOGgxpbnZpdGVzLnZpZXcSbQoPR2V0R3VpbGRNZW1iZXJzEigucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZE1lbWJlcnNSZXF1ZXN0GikucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZE1lbWJlcnNSZXNwb25zZSIFmkQCCAEScAoQR2V0R3VpbGRDaGFubmVscxIpLnByb3RvY29sLmNoYXQudjEuR2V0R3VpbGRDaGFubmVsc1JlcXVlc3QaKi5wcm90b2NvbC5jaGF0LnYxLkdldEd1aWxkQ2hhbm5lbHNSZXNwb25zZSIFmkQCCAESiAEKEkdldENoYW5uZWxNZXNzYWdlcxIrLnByb3RvY29sLmNoYXQudjEuR2V0Q2hhbm5lbE1lc3NhZ2VzUmVxdWVzdBosLnByb3RvY29sLmNoYXQudjEuR2V0Q2hhbm5lbE1lc3NhZ2VzUmVzcG9uc2UiF5pEAggBmkQPGg1tZXNzYWdlcy52aWV3EnAKCkdldE1lc3NhZ2USIy5wcm90b2NvbC5jaGF0LnYxLkdldE1lc3NhZ2VSZXF1ZXN0GiQucHJvdG9jb2wuY2hhdC52MS5HZXRNZXNzYWdlUmVzcG9uc2UiF5pEAggBmkQPGg1tZXNzYWdlcy52aWV3EqYBChZVcGRhdGVHdWlsZEluZm9ybWF0aW9uEi8ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVHdWlsZEluZm9ybWF0aW9uUmVxdWVzdBowLnByb3RvY29sLmNoYXQudjEuVXBkYXRlR3VpbGRJbmZvcm1hdGlvblJlc3BvbnNlIimaRAIIAZpEIRofZ3VpbGQubWFuYWdlLmNoYW5nZS1pbmZvcm1hdGlvbhKvAQoYVXBkYXRlQ2hhbm5lbEluZm9ybWF0aW9uEjEucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVDaGFubmVsSW5mb3JtYXRpb25SZXF1ZXN0GjIucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVDaGFubmVsSW5mb3JtYXRpb25SZXNwb25zZSIsmkQCCAGaRCQaImNoYW5uZWxzLm1hbmFnZS5jaGFuZ2UtaW5mb3JtYXRpb24SjwEKElVwZGF0ZUNoYW5uZWxPcmRlchIrLnByb3RvY29sLmNoYXQudjEuVXBkYXRlQ2hhbm5lbE9yZGVyUmVxdWVzdBosLnByb3RvY29sLmNoYXQudjEuVXBkYXRlQ2hhbm5lbE9yZGVyUmVzcG9uc2UiHppEAggBmkQWGhRjaGFubmVscy5tYW5hZ2UubW92ZRKYAQoVVXBkYXRlQWxsQ2hhbm5lbE9yZGVyEi4ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVBbGxDaGFubmVsT3JkZXJSZXF1ZXN0Gi8ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVBbGxDaGFubmVsT3JkZXJSZXNwb25zZSIemkQCCAGaRBYaFGNoYW5uZWxzLm1hbmFnZS5tb3ZlEo4BChRVcGRhdGVNZXNzYWdlQ29udGVudBItLnByb3RvY29sLmNoYXQudjEuVXBkYXRlTWVzc2FnZUNvbnRlbnRSZXF1ZXN0Gi4ucHJvdG9jb2wuY2hhdC52MS5VcGRhdGVNZXNzYWdlQ29udGVudFJlc3BvbnNlIheaRAIIAZpEDxoNbWVzc2FnZXMuc2VuZBJmCgtEZWxldGVHdWlsZBIkLnByb3RvY29sLmNoYXQudjEuRGVsZXRlR3VpbGRSZXF1ZXN0GiUucHJvdG9jb2wuY2hhdC52MS5EZWxldGVHdWlsZFJlc3BvbnNlIgqaRAIIAZpEAiABEn4KDERlbGV0ZUludml0ZRIlLnByb3RvY29sLmNoYXQudjEuRGVsZXRlSW52aXRlUmVxdWVzdBomLnByb3RvY29sLmNoYXQudjEuRGVsZXRlSW52aXRlUmVzcG9uc2UiH5pEAggBmkQXGhVpbnZpdGVzLm1hbmFnZS5kZWxldGUSggEKDURlbGV0ZUNoYW5uZWwSJi5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZUNoYW5uZWxSZXF1ZXN0GicucHJvdG9jb2wuY2hhdC52MS5EZWxldGVDaGFubmVsUmVzcG9uc2UiIJpEAggBmkQYGhZjaGFubmVscy5tYW5hZ2UuZGVsZXRlEmcKDURlbGV0ZU1lc3NhZ2USJi5wcm90b2NvbC5jaGF0LnYxLkRlbGV0ZU1lc3NhZ2VSZXF1ZXN0GicucHJvdG9jb2wuY2hhdC52MS5EZWxldGVNZXNzYWdlUmVzcG9uc2UiBZpEAggBElsKCUpvaW5HdWlsZBIiLnByb3RvY29sLmNoYXQudjEuSm9pbkd1aWxkUmVxdWVzdBojLnByb3RvY29sLmNoYXQudjEuSm9pbkd1aWxkUmVzcG9uc2UiBZpEAggBEl4KCkxlYXZlR3VpbGQSIy5wcm90b2NvbC5jaGF0LnYxLkxlYXZlR3VpbGRSZXF1ZXN0GiQucHJvdG9jb2wuY2hhdC52MS5MZWF2ZUd1aWxkUmVzcG9uc2UiBZpEAggBEnsKDVRyaWdnZXJBY3Rpb24SJi5wcm90b2NvbC5jaGF0LnYxLlRyaWdnZXJBY3Rpb25SZXF1ZXN0GicucHJvdG9jb2wuY2hhdC52MS5UcmlnZ2VyQWN0aW9uUmVzcG9uc2UiGZpEAggBmkQRGg9hY3Rpb25zLnRyaWdnZXIScwoLU2VuZE1lc3NhZ2USJC5wcm90b2NvbC5jaGF0LnYxLlNlbmRNZXNzYWdlUmVxdWVzdBolLnByb3RvY29sLmNoYXQudjEuU2VuZE1lc3NhZ2VSZXNwb25zZSIXmkQCCAGaRA8aDW1lc3NhZ2VzLnNlbmQSZwoNSGFzUGVybWlzc2lvbhImLnByb3RvY29sLmNoYXQudjEuSGFzUGVybWlzc2lvblJlcXVlc3QaJy5wcm90b2NvbC5jaGF0LnYxLkhhc1Blcm1pc3Npb25SZXNwb25zZSIFmkQCCAEShQEKDlNldFBlcm1pc3Npb25zEicucHJvdG9jb2wuY2hhdC52MS5TZXRQZXJtaXNzaW9uc1JlcXVlc3QaKC5wcm90b2NvbC5jaGF0LnYxLlNldFBlcm1pc3Npb25zUmVzcG9uc2UiIJpEAggBmkQYGhZwZXJtaXNzaW9ucy5tYW5hZ2Uuc2V0EoUBCg5HZXRQZXJtaXNzaW9ucxInLnByb3RvY29sLmNoYXQudjEuR2V0UGVybWlzc2lvbnNSZXF1ZXN0GigucHJvdG9jb2wuY2hhdC52MS5HZXRQZXJtaXNzaW9uc1Jlc3BvbnNlIiCaRAIIAZpEGBoWcGVybWlzc2lvbnMubWFuYWdlLmdldBJpCghNb3ZlUm9sZRIhLnByb3RvY29sLmNoYXQudjEuTW92ZVJvbGVSZXF1ZXN0GiIucHJvdG9jb2wuY2hhdC52MS5Nb3ZlUm9sZVJlc3BvbnNlIhaaRAIIAZpEDhoMcm9sZXMubWFuYWdlEnUKDUdldEd1aWxkUm9sZXMSJi5wcm90b2NvbC5jaGF0LnYxLkdldEd1aWxkUm9sZXNSZXF1ZXN0GicucHJvdG9jb2wuY2hhdC52MS5HZXRHdWlsZFJvbGVzUmVzcG9uc2UiE5pEAggBmkQLGglyb2xlcy5nZXQSdQoMQWRkR3VpbGRSb2xlEiUucHJvdG9jb2wuY2hhdC52MS5BZGRHdWlsZFJvbGVSZXF1ZXN0GiYucHJvdG9jb2wuY2hhdC52MS5BZGRHdWlsZFJvbGVSZXNwb25zZSIWmkQCCAGaRA4aDHJvbGVzLm1hbmFnZRJ+Cg9Nb2RpZnlHdWlsZFJvbGUSKC5wcm90b2NvbC5jaGF0LnYxLk1vZGlmeUd1aWxkUm9sZVJlcXVlc3QaKS5wcm90b2NvbC5jaGF0LnYxLk1vZGlmeUd1aWxkUm9sZVJlc3BvbnNlIhaaRAIIAZpEDhoMcm9sZXMubWFuYWdlEn4KD0RlbGV0ZUd1aWxkUm9sZRIoLnByb3RvY29sLmNoYXQudjEuRGVsZXRlR3VpbGRSb2xlUmVxdWVzdBopLnByb3RvY29sLmNoYXQudjEuRGVsZXRlR3VpbGRSb2xlUmVzcG9uc2UiFppEAggBmkQOGgxyb2xlcy5tYW5hZ2USgwEKD01hbmFnZVVzZXJSb2xlcxIoLnByb3RvY29sLmNoYXQudjEuTWFuYWdlVXNlclJvbGVzUmVxdWVzdBopLnByb3RvY29sLmNoYXQudjEuTWFuYWdlVXNlclJvbGVzUmVzcG9uc2UiG5pEAggBmkQTGhFyb2xlcy51c2VyLm1hbmFnZRJkCgxHZXRVc2VyUm9sZXMSJS5wcm90b2NvbC5jaGF0LnYxLkdldFVzZXJSb2xlc1JlcXVlc3QaJi5wcm90b2NvbC5jaGF0LnYxLkdldFVzZXJSb2xlc1Jlc3BvbnNlIgWaRAIIARJkCgZUeXBpbmcSHy5wcm90b2NvbC5jaGF0LnYxLlR5cGluZ1JlcXVlc3QaIC5wcm90b2NvbC5jaGF0LnYxLlR5cGluZ1Jlc3BvbnNlIheaRAIIAZpEDxoNbWVzc2FnZXMuc2VuZBJkCgxQcmV2aWV3R3VpbGQSJS5wcm90b2NvbC5jaGF0LnYxLlByZXZpZXdHdWlsZFJlcXVlc3QaJi5wcm90b2NvbC5jaGF0LnYxLlByZXZpZXdHdWlsZFJlc3BvbnNlIgWaRAIIABKOAQoOR2V0QmFubmVkVXNlcnMSJy5wcm90b2NvbC5jaGF0LnYxLkdldEJhbm5lZFVzZXJzUmVxdWVzdBooLnByb3RvY29sLmNoYXQudjEuR2V0QmFubmVkVXNlcnNSZXNwb25zZSIpmkQCCAGaRCEaH2d1aWxkLm1hbmFnZS5jaGFuZ2UtaW5mb3JtYXRpb24SaQoHQmFuVXNlchIgLnByb3RvY29sLmNoYXQudjEuQmFuVXNlclJlcXVlc3QaIS5wcm90b2NvbC5jaGF0LnYxLkJhblVzZXJSZXNwb25zZSIZmkQCCAGaRBEaD3VzZXIubWFuYWdlLmJhbhJtCghLaWNrVXNlchIhLnByb3RvY29sLmNoYXQudjEuS2lja1VzZXJSZXF1ZXN0GiIucHJvdG9jb2wuY2hhdC52MS5LaWNrVXNlclJlc3BvbnNlIhqaRAIIAZpEEhoQdXNlci5tYW5hZ2Uua2ljaxJxCglVbmJhblVzZXISIi5wcm90b2NvbC5jaGF0LnYxLlVuYmFuVXNlclJlcXVlc3QaIy5wcm90b2NvbC5jaGF0LnYxLlVuYmFuVXNlclJlc3BvbnNlIhuaRAIIAZpEExoRdXNlci5tYW5hZ2UudW5iYW4ShQEKEUdldFBpbm5lZE1lc3NhZ2VzEioucHJvdG9jb2wuY2hhdC52MS5HZXRQaW5uZWRNZXNzYWdlc1JlcXVlc3QaKy5wcm90b2NvbC5jaGF0LnYxLkdldFBpbm5lZE1lc3NhZ2VzUmVzcG9uc2UiF5pEAggBmkQPGg1tZXNzYWdlcy52aWV3EnQKClBpbk1lc3NhZ2USIy5wcm90b2NvbC5jaGF0LnYxLlBpbk1lc3NhZ2VSZXF1ZXN0GiQucHJvdG9jb2wuY2hhdC52MS5QaW5NZXNzYWdlUmVzcG9uc2UiG5pEAggBmkQTGhFtZXNzYWdlcy5waW5zLmFkZBJ9CgxVbnBpbk1lc3NhZ2USJS5wcm90b2NvbC5jaGF0LnYxLlVucGluTWVzc2FnZVJlcXVlc3QaJi5wcm90b2NvbC5jaGF0LnYxLlVucGluTWVzc2FnZVJlc3BvbnNlIh6aRAIIAZpEFhoUbWVzc2FnZXMucGlucy5yZW1vdmUSaAoMU3RyZWFtRXZlbnRzEiUucHJvdG9jb2wuY2hhdC52MS5TdHJlYW1FdmVudHNSZXF1ZXN0GiYucHJvdG9jb2wuY2hhdC52MS5TdHJlYW1FdmVudHNSZXNwb25zZSIFmkQCCAEoATABEnwKC0FkZFJlYWN0aW9uEiQucHJvdG9jb2wuY2hhdC52MS5BZGRSZWFjdGlvblJlcXVlc3QaJS5wcm90b2NvbC5jaGF0LnYxLkFkZFJlYWN0aW9uUmVzcG9uc2UiIJpEAggBmkQYGhZtZXNzYWdlcy5yZWFjdGlvbnMuYWRkEogBCg5SZW1vdmVSZWFjdGlvbhInLnByb3RvY29sLmNoYXQudjEuUmVtb3ZlUmVhY3Rpb25SZXF1ZXN0GigucHJvdG9jb2wuY2hhdC52MS5SZW1vdmVSZWFjdGlvblJlc3BvbnNlIiOaRAIIAZpEGxoZbWVzc2FnZXMucmVhY3Rpb25zLnJlbW92ZRJvCg5HcmFudE93bmVyc2hpcBInLnByb3RvY29sLmNoYXQudjEuR3JhbnRPd25lcnNoaXBSZXF1ZXN0GigucHJvdG9jb2wuY2hhdC52MS5HcmFudE93bmVyc2hpcFJlc3BvbnNlIgqaRAIIAZpEAiABEnIKD0dpdmVVcE93bmVyc2hpcBIoLnByb3RvY29sLmNoYXQudjEuR2l2ZVVwT3duZXJzaGlwUmVxdWVzdBopLnByb3RvY29sLmNoYXQudjEuR2l2ZVVwT3duZXJzaGlwUmVzcG9uc2UiCppEAggBmkQCIAE=');
